// CSIT Entrance — Predicted Practice Papers, Model Sets 1-4
// Each question: t=text, o=[4 options], c=correct index (0-3), e=explanation
// Source: TU IOST B.Sc. CSIT Entrance Predicted Practice Paper PDF (with official answer key).
// NOTE: The printed answer key has exactly one typo, fixed here: Set 1 Q85 ("an honest man").
// NOTE: Off-syllabus math questions (permutation/combination, binomial, probability, statistics,
// vectors) were replaced with syllabus topics: sets, functions, complex numbers, polynomial
// equations, sequences, trigonometry, coordinate geometry, L'Hospital's rule, calculus applications.

const QUESTIONS = {
1: [
// ---- Mathematics (1-25) ----
{t:"Number of subsets of a set having 4 elements is", o:["8","16","12","4"], c:1, e:"A set with n elements has 2ⁿ subsets. Here 2⁴ = 16."},
{t:"If i = √-1, then i^50 equals", o:["1","-1","i","-i"], c:1, e:"Powers of i cycle every 4: i⁵⁰ = i^(48+2) = (i⁴)¹² · i² = 1 · (-1) = -1."},
{t:"The sum of the roots of x² - 7x + 12 = 0 is", o:["7","12","-7","5"], c:0, e:"For ax²+bx+c=0, sum of roots = -b/a = -(-7)/1 = 7."},
{t:"The product of the roots of 3x² + 5x - 2 = 0 is", o:["-2/3","2/3","5/3","-5/3"], c:0, e:"Product of roots = c/a = -2/3."},
{t:"If f(x) = 2x + 3, then f(f(1)) is", o:["13","11","10","5"], c:0, e:"f(1) = 2(1)+3 = 5, then f(5) = 2(5)+3 = 13."},
{t:"The modulus of the complex number 3 + 4i is", o:["5","7","√7","25"], c:0, e:"|3+4i| = √(3²+4²) = √25 = 5."},
{t:"The 10th term of the AP 3, 7, 11, ... is", o:["39","40","43","36"], c:0, e:"aₙ = a + (n-1)d = 3 + 9(4) = 39."},
{t:"The sum 2 + 4 + 6 + ... + 20 equals", o:["100","110","120","90"], c:1, e:"10 terms, sum = n(a+l)/2 = 10(2+20)/2 = 110."},
{t:"The 8th term of the GP 1, 2, 4, 8, ... is", o:["64","128","256","32"], c:1, e:"aₙ = a·rⁿ⁻¹ = 1·2⁷ = 128."},
{t:"The sum to infinity of 1 + 1/2 + 1/4 + ... is", o:["1","2","3","∞"], c:1, e:"S∞ = a/(1-r) = 1/(1-1/2) = 2."},
{t:"If the 3rd term of an AP is 10 and the 7th term is 26, the common difference is", o:["4","3","2","6"], c:0, e:"a₇ - a₃ = 4d = 26 - 10 = 16, so d = 4."},
{t:"The value of log₃ 81 is", o:["3","4","27","9"], c:1, e:"3⁴ = 81, so log₃ 81 = 4."},
{t:"The determinant of [[1, 2], [3, 4]] is", o:["2","-2","10","-10"], c:1, e:"det = (1)(4) - (2)(3) = 4 - 6 = -2."},
{t:"The value of sin 60° is", o:["1/2","√3/2","1","√2/2"], c:1, e:"Standard value: sin 60° = √3/2."},
{t:"The value of tan 30° is", o:["√3","1/√3","1","0"], c:1, e:"Standard value: tan 30° = 1/√3."},
{t:"If sinθ = 3/5 and θ is acute, then cosθ is", o:["4/5","3/4","5/4","5/3"], c:0, e:"3-4-5 right triangle: cosθ = adjacent/hyp = 4/5."},
{t:"The distance between the points (1, 2) and (4, 6) is", o:["5","√5","7","25"], c:0, e:"d = √((4-1)²+(6-2)²) = √(9+16) = √25 = 5."},
{t:"The slope of the line 2x + 3y = 6 is", o:["2/3","-2/3","3/2","-3/2"], c:1, e:"Rewrite as y = -(2/3)x + 2, so slope = -2/3."},
{t:"The centre of the circle x² + y² - 4x - 6y + 9 = 0 is", o:["(2, 3)","(-2, -3)","(4, 6)","(-4, -6)"], c:0, e:"Centre = (-(-4)/2, -(-6)/2) = (2, 3)."},
{t:"The value of lim(x → 0) (sin x)/x is", o:["0","1","∞","undefined"], c:1, e:"Standard calculus limit: lim(x→0) sinx/x = 1."},
{t:"The derivative of cos x with respect to x is", o:["sin x","-sin x","cos x","-cos x"], c:1, e:"d/dx(cos x) = -sin x."},
{t:"The value of ∫ cos x dx is", o:["sin x + c","-sin x + c","cos x + c","tan x + c"], c:0, e:"∫cos x dx = sin x + c."},
{t:"Using L'Hospital's rule, the value of lim(x → 0) (eˣ - 1)/x is", o:["1","0","e","∞"], c:0, e:"0/0 form → differentiate top and bottom: lim eˣ/1 = e⁰ = 1."},
{t:"The slope of the tangent to the curve y = x² at x = 1 is", o:["2","1","0","4"], c:0, e:"dy/dx = 2x; at x = 1, slope = 2."},
{t:"The area under the line y = 2x from x = 0 to x = 2 is", o:["4","2","8","1"], c:0, e:"Area = ∫₀² 2x dx = [x²]₀² = 4."},
// ---- Physics (26-50) ----
{t:"The SI unit of force is", o:["Joule","Newton","Watt","Pascal"], c:1, e:"Force is measured in newtons (N), by definition F = ma."},
{t:"The dimensional formula of velocity is", o:["[LT⁻¹]","[LT⁻²]","[L]","[T⁻¹]"], c:0, e:"Velocity = distance/time → [L]/[T] = [LT⁻¹]."},
{t:"A body moving with uniform velocity has an acceleration of", o:["zero","positive value","negative value","infinite value"], c:0, e:"Uniform velocity means no change in velocity, so acceleration = 0."},
{t:"Newton's second law of motion is expressed as", o:["F = ma","F = mv","F = m/a","F = ma²"], c:0, e:"Newton's second law: force = mass × acceleration."},
{t:"At the highest point of its path, a ball thrown vertically upward has a velocity of", o:["zero","maximum","g","mg"], c:0, e:"At the peak of vertical motion, vertical velocity momentarily becomes zero."},
{t:"The SI unit of work is", o:["Newton","Joule","Watt","Pascal"], c:1, e:"Work = force × displacement, measured in joules (J)."},
{t:"The kinetic energy of a body of mass m moving with velocity v is", o:["½mv²","mv²","½mv","mgh"], c:0, e:"Kinetic energy formula: KE = ½mv²."},
{t:"The SI unit of power is", o:["Watt","Joule","Newton","Pascal"], c:0, e:"Power = work/time, measured in watts (W)."},
{t:"The approximate value of acceleration due to gravity on earth is", o:["9.8 m/s²","8.9 m/s²","10.8 m/s²","6.8 m/s²"], c:0, e:"Standard value used: g ≈ 9.8 m/s²."},
{t:"The weight of a body of mass 10 kg on the earth's surface is about", o:["10 N","98 N","9.8 N","100 N"], c:1, e:"Weight = mg = 10 × 9.8 = 98 N."},
{t:"The escape velocity from the earth is approximately", o:["11.2 km/s","7.9 km/s","8 km/s","9.8 km/s"], c:0, e:"Standard known value: escape velocity ≈ 11.2 km/s."},
{t:"The time period of a simple pendulum depends on its", o:["mass","length","amplitude","material"], c:1, e:"T = 2π√(L/g) — depends on length L (and g), not mass or material."},
{t:"The speed of sound in air at room temperature is approximately", o:["340 m/s","3×10⁸ m/s","1500 m/s","150 m/s"], c:0, e:"Speed of sound in air ≈ 340 m/s at room temperature."},
{t:"The speed of light in vacuum is", o:["3×10⁸ m/s","3×10⁶ m/s","340 m/s","1.5×10⁸ m/s"], c:0, e:"c = 3×10⁸ m/s is the standard speed of light in vacuum."},
{t:"The SI unit of frequency is", o:["Hertz","Newton","Watt","Decibel"], c:0, e:"Frequency is measured in hertz (Hz), cycles per second."},
{t:"A convex lens is used to ______ a beam of light.", o:["converge","diverge","absorb","reflect"], c:0, e:"A convex (converging) lens bends parallel rays inward to converge them."},
{t:"Total internal reflection occurs when light travels from", o:["denser to rarer medium","rarer to denser medium","same medium","none of these"], c:0, e:"TIR happens when light goes from a denser to a rarer medium beyond the critical angle."},
{t:"The SI unit of electric current is", o:["Ampere","Volt","Ohm","Coulomb"], c:0, e:"Electric current is measured in amperes (A)."},
{t:"Ohm's law is written as", o:["V = IR","V = I/R","V = R/I","I = VR"], c:0, e:"Ohm's law: Voltage = Current × Resistance."},
{t:"The SI unit of resistance is", o:["Ohm","Volt","Ampere","Watt"], c:0, e:"Electrical resistance is measured in ohms (Ω)."},
{t:"The charge on an electron is approximately", o:["1.6×10⁻¹⁹ C","9.1×10⁻³¹ C","6.6×10⁻³⁴ C","3×10⁸ C"], c:0, e:"Elementary charge e ≈ 1.6×10⁻¹⁹ C (9.1×10⁻³¹ kg is its mass, not charge)."},
{t:"The photoelectric effect was explained by", o:["Einstein","Newton","Bohr","Rutherford"], c:0, e:"Einstein explained the photoelectric effect (1905) using light quanta/photons."},
{t:"The nucleus of an atom contains", o:["protons and neutrons","protons and electrons","only protons","neutrons and electrons"], c:0, e:"The nucleus is made of protons and neutrons; electrons orbit outside it."},
{t:"At absolute zero temperature, a pure semiconductor behaves as an", o:["insulator","conductor","superconductor","metal"], c:0, e:"At 0 K, no electrons have thermal energy to jump the band gap, so it acts as an insulator."},
{t:"Two 4 Ω resistors connected in parallel give an equivalent resistance of", o:["8 Ω","2 Ω","4 Ω","16 Ω"], c:1, e:"Parallel: 1/R = 1/4 + 1/4 = 1/2 → R = 2 Ω."},
// ---- Chemistry (51-75) ----
{t:"The atomic number of an element is equal to the number of", o:["protons","neutrons","electrons and neutrons","nucleons"], c:0, e:"Atomic number Z = number of protons in the nucleus."},
{t:"In a neutral atom, the number of electrons equals the", o:["atomic number","mass number","number of neutrons","none of these"], c:0, e:"A neutral atom has equal protons and electrons, so electrons = atomic number."},
{t:"Isotopes of an element have", o:["same atomic number but different mass number","same mass number but different atomic number","same atomic and mass number","different atomic and mass number"], c:0, e:"Isotopes share proton count (atomic number) but differ in neutron count (mass number)."},
{t:"The modern periodic table is arranged in order of increasing", o:["atomic number","atomic mass","valency","density"], c:0, e:"Mendeleev used atomic mass; the modern table uses increasing atomic number."},
{t:"The most electronegative element is", o:["Fluorine","Oxygen","Chlorine","Nitrogen"], c:0, e:"Fluorine has the highest electronegativity (≈4.0 on the Pauling scale) of all elements."},
{t:"The number of periods in the modern periodic table is", o:["7","8","18","9"], c:0, e:"The modern periodic table has 7 periods (rows)."},
{t:"Group 1 elements are commonly called", o:["alkali metals","alkaline earth metals","halogens","noble gases"], c:0, e:"Group 1 (Li, Na, K...) are the alkali metals."},
{t:"An ionic bond is formed by the", o:["transfer of electrons","sharing of electrons","overlap of orbitals","none of these"], c:0, e:"Ionic bonds form when electrons transfer from one atom to another, creating ions."},
{t:"A covalent bond is formed by the", o:["sharing of electrons","transfer of electrons","gain of protons","none of these"], c:0, e:"Covalent bonds form when atoms share electron pairs."},
{t:"Avogadro's number is", o:["6.022×10²³","6.626×10⁻³⁴","1.6×10⁻¹⁹","3×10⁸"], c:0, e:"Avogadro's number NA = 6.022×10²³ per mole."},
{t:"The molar mass of water (H₂O) is", o:["18 g/mol","16 g/mol","2 g/mol","20 g/mol"], c:0, e:"H₂O = 2(1) + 16 = 18 g/mol."},
{t:"The number of moles present in 36 g of water is", o:["1","2","3","0.5"], c:1, e:"Moles = mass/molar mass = 36/18 = 2."},
{t:"The pH of a neutral solution at 25 °C is", o:["7","0","14","1"], c:0, e:"Neutral solutions (like pure water) have pH = 7 at 25 °C."},
{t:"Acids have a pH value that is", o:["less than 7","greater than 7","equal to 7","equal to 14"], c:0, e:"Acidic solutions have pH < 7."},
{t:"Oxidation is defined as the", o:["loss of electrons","gain of electrons","sharing of electrons","none of these"], c:0, e:"Oxidation = loss of electrons (remember: OIL RIG)."},
{t:"A catalyst is a substance that", o:["increases the rate of reaction without being consumed","decreases the rate permanently","has no effect on the rate","stops the reaction"], c:0, e:"A catalyst speeds up a reaction but is chemically unchanged/not consumed at the end."},
{t:"The equation PV = nRT is known as the", o:["ideal gas equation","Boyle's law only","Charles's law only","none of these"], c:0, e:"PV = nRT is the ideal gas equation, combining Boyle's, Charles's, and Avogadro's laws."},
{t:"At STP, one mole of any gas occupies a volume of", o:["22.4 L","11.2 L","24 L","1 L"], c:0, e:"Molar volume of an ideal gas at STP is 22.4 L."},
{t:"Blue vitriol is chemically", o:["CuSO4·5H2O","FeSO4·7H2O","ZnSO4","MgSO4"], c:0, e:"Blue vitriol is copper(II) sulfate pentahydrate, CuSO₄·5H₂O."},
{t:"Rusting of iron is an example of", o:["oxidation","reduction","neutralisation","none of these"], c:0, e:"Rusting is iron reacting with oxygen/water — an oxidation process."},
{t:"The simplest hydrocarbon is", o:["methane","ethane","benzene","ethene"], c:0, e:"Methane (CH₄), with just one carbon, is the simplest hydrocarbon."},
{t:"The general formula of an alkane is", o:["CnH2n+2","CnH2n","CnH2n-2","CnHn"], c:0, e:"Saturated alkanes follow CₙH₂ₙ₊₂ (e.g., methane CH₄, n=1: 2(1)+2=4)."},
{t:"The functional group present in ethanol is", o:["-OH","-CHO","-COOH","-NH2"], c:0, e:"Ethanol is an alcohol, characterised by the hydroxyl (-OH) group."},
{t:"Vinegar mainly contains", o:["acetic acid","citric acid","sulphuric acid","formic acid"], c:0, e:"Vinegar is a dilute solution of acetic acid (~4-8%)."},
{t:"The polymer obtained from ethene is", o:["polythene","PVC","nylon","teflon"], c:0, e:"Polymerising ethene (ethylene) monomers gives polythene (polyethylene)."},
// ---- English (76-90) ----
{t:'Choose the word nearest in meaning to "abundant".', o:["scarce","plentiful","empty","rare"], c:1, e:'"Abundant" means existing in large quantity — closest synonym is "plentiful".'},
{t:'Choose the word opposite in meaning to "ancient".', o:["old","modern","historic","aged"], c:1, e:'"Ancient" (very old) is opposite to "modern".'},
{t:"Fill in the blank: He ______ to school every day.", o:["go","goes","going","gone"], c:1, e:'Third-person singular subject "He" with a habitual action needs the -s form: "goes".'},
{t:"Fill in the blank: She has been working ______ morning.", o:["since","for","from","at"], c:0, e:'"Since" is used with a specific starting point in time (like "morning"), while "for" is used with a duration.'},
{t:'The correct plural of "child" is', o:["childs","children","childrens","child"], c:1, e:'"Child" has the irregular plural "children".'},
{t:'Change into passive voice: "He wrote a letter."', o:["A letter was written by him","A letter is written by him","He was written a letter","A letter has written by him"], c:0, e:"Past simple active → past simple passive: subject-verb 'wrote' becomes 'was written by'."},
{t:"Fill in the blank: One of the boys ______ absent.", o:["is","are","were","have"], c:0, e:'"One" is the true (singular) subject of the sentence, so it takes "is".'},
{t:"Choose the correctly spelt word.", o:["recieve","receive","receeve","receve"], c:1, e:'"i before e except after c" — correct spelling is "receive".'},
{t:'The idiom "to break the ice" means', o:["to start a conversation","to break glass","to feel cold","to quarrel"], c:0, e:'"Break the ice" idiomatically means to ease tension and start a conversation.'},
{t:"Fill in the blank with the correct article: ______ honest man.", o:["a","an","the","no article"], c:1, e:'"Honest" begins with a silent "h", so it starts with a vowel sound → "an honest man". (Note: the printed answer key has a typo here — it lists "a"; the grammatically correct choice is "an".)'},
{t:"Fill in the blank: Neither of them ______ coming.", o:["is","are","were","have"], c:0, e:'"Neither...nor" constructions take a singular verb: "is".'},
{t:'The comparative form of "good" is', o:["gooder","better","best","more good"], c:1, e:'"Good" is irregular: good → better (comparative) → best (superlative).'},
{t:"Fill in the blank: He is afraid ______ dogs.", o:["of","from","with","at"], c:0, e:'The fixed preposition pairing is "afraid of".'},
{t:'Choose the word nearest in meaning to "brave".', o:["timid","courageous","weak","fearful"], c:1, e:'"Brave" means having courage — nearest synonym is "courageous".'},
{t:"Choose the correctly punctuated sentence.", o:["Where are you going.","Where are you going?","where are you going?","Where are you going!"], c:1, e:"A question needs a capital first letter and a question mark: \"Where are you going?\""},
// ---- Computer (91-100) ----
{t:'The "brain" of a computer is the', o:["RAM","CPU","ROM","Monitor"], c:1, e:"The CPU (Central Processing Unit) executes instructions and is called the brain of the computer."},
{t:"RAM stands for", o:["Random Access Memory","Read Access Memory","Rapid Access Memory","Random Add Memory"], c:0, e:"RAM = Random Access Memory, volatile memory used for temporary data."},
{t:"One byte is equal to", o:["4 bits","8 bits","16 bits","1024 bits"], c:1, e:"By definition, 1 byte = 8 bits."},
{t:"The binary equivalent of the decimal number 5 is", o:["101","110","111","100"], c:0, e:"5 = 4+1 = 2²+2⁰ → binary 101."},
{t:"Which of the following is an input device?", o:["Monitor","Printer","Keyboard","Speaker"], c:2, e:"A keyboard sends data into the computer, making it an input device (the others are outputs)."},
{t:"The full form of CPU is", o:["Central Processing Unit","Computer Personal Unit","Central Program Unit","Control Processing Unit"], c:0, e:"CPU = Central Processing Unit."},
{t:"Which of the following is an operating system?", o:["MS Word","Windows","Chrome","Excel"], c:1, e:"Windows manages hardware/software resources — it's an operating system; the others are applications."},
{t:"WWW stands for", o:["World Wide Web","World Web Wide","Wide World Web","Web World Wide"], c:0, e:"WWW = World Wide Web."},
{t:"Which of the following is a volatile memory?", o:["ROM","RAM","Hard disk","CD"], c:1, e:"RAM loses its data when power is off, making it volatile; ROM/hard disk/CD are non-volatile."},
{t:"The decimal equivalent of the binary number 1010 is", o:["8","10","12","16"], c:1, e:"1010₂ = 1(8)+0(4)+1(2)+0(1) = 10."},
],

2: [
// ---- Mathematics (1-25) ----
{t:"If a set has 5 elements, the number of proper subsets is", o:["31","32","30","16"], c:0, e:"Total subsets = 2⁵ = 32; proper subsets exclude the set itself, giving 31."},
{t:"The value of i^101 is", o:["i","-i","1","-1"], c:0, e:"i^101 = i^(100+1) = (i⁴)²⁵·i = 1·i = i."},
{t:"The sum of the roots of x² - 9 = 0 is", o:["0","9","-9","3"], c:0, e:"Here b = 0, so sum of roots = -b/a = 0 (roots are +3 and -3)."},
{t:"The sum of the roots of 2x² - 8x + 6 = 0 is", o:["4","3","-4","8"], c:0, e:"Sum of roots = -b/a = -(-8)/2 = 4."},
{t:"If A = {1, 2, 3} and B = {3, 4}, then A ∩ B is", o:["{3}","{1, 2, 3, 4}","{1, 2}","∅"], c:0, e:"Intersection keeps only the common elements: {3}."},
{t:"The conjugate of the complex number 2 - 3i is", o:["2 + 3i","-2 + 3i","-2 - 3i","3 - 2i"], c:0, e:"The conjugate flips the sign of the imaginary part: 2 + 3i."},
{t:"The 5th term of the AP 1, 4, 7, ... is", o:["13","16","10","19"], c:0, e:"aₙ = a+(n-1)d = 1 + 4(3) = 13."},
{t:"The sum of the first 20 natural numbers is", o:["210","200","190","220"], c:0, e:"Sum = n(n+1)/2 = 20(21)/2 = 210."},
{t:"In a GP with first term 3 and common ratio 2, the 5th term is", o:["48","24","96","16"], c:0, e:"a₅ = a·r⁴ = 3·16 = 48."},
{t:"The sum to infinity of 2 + 1 + 1/2 + ... is", o:["4","3","2","∞"], c:0, e:"r = 1/2, S∞ = a/(1-r) = 2/(1/2) = 4."},
{t:"If one root of x² - 5x + 6 = 0 is 2, the other root is", o:["3","-3","6","-2"], c:0, e:"Product of roots = c/a = 6, so the other root = 6/2 = 3 (check: sum 2+3 = 5 ✓)."},
{t:"The value of log₂ 64 is", o:["6","5","8","4"], c:0, e:"2⁶ = 64, so log₂ 64 = 6."},
{t:"The value of log 1 (to any base) is", o:["0","1","10","undefined"], c:0, e:"Any base raised to the power 0 equals 1, so log 1 = 0 always."},
{t:"The determinant of [[3, 0], [0, 3]] is", o:["9","6","0","3"], c:0, e:"det = (3)(3) - (0)(0) = 9."},
{t:"The value of cos 60° is", o:["1/2","√3/2","1","0"], c:0, e:"Standard value: cos 60° = 1/2."},
{t:"The value of sin 45° is", o:["1/√2","√3/2","1/2","1"], c:0, e:"Standard value: sin 45° = 1/√2."},
{t:"The value of cot 45° is", o:["1","0","√3","1/√3"], c:0, e:"cot 45° = cos45°/sin45° = 1 (since sin45°=cos45°)."},
{t:"If cosθ = 0 and 0° ≤ θ ≤ 180°, then θ is", o:["0°","45°","90°","180°"], c:2, e:"cos 90° = 0, and 90° lies in the given range."},
{t:"The distance between the points (0, 0) and (6, 8) is", o:["10","14","8","6"], c:0, e:"d = √(6²+8²) = √(36+64) = √100 = 10."},
{t:"The slope of the x-axis is", o:["0","1","∞","-1"], c:0, e:"The x-axis is horizontal, so its slope is 0."},
{t:"The radius of the circle x² + y² = 49 is", o:["7","49","√7","14"], c:0, e:"Comparing to x²+y²=r²: r² = 49, so r = 7."},
{t:"The derivative of x² + 3x with respect to x is", o:["2x + 3","x + 3","2x","2x + 3x"], c:0, e:"d/dx(x²) = 2x, d/dx(3x) = 3, sum = 2x + 3."},
{t:"The value of ∫ x² dx is", o:["x³/3 + c","x³ + c","2x + c","3x² + c"], c:0, e:"Power rule for integration: ∫xⁿdx = xⁿ⁺¹/(n+1) + c → x³/3 + c."},
{t:"The value of lim(x→2) (x² - 4)/(x - 2) is", o:["4","0","2","undefined"], c:0, e:"Factor: (x-2)(x+2)/(x-2) = x+2 → limit as x→2 is 4."},
{t:"Using L'Hospital's rule, the value of lim(x → 0) (1 - cos x)/x² is", o:["1/2","0","1","∞"], c:0, e:"0/0 form → sinx/2x (still 0/0) → cosx/2 → 1/2."},
// ---- Physics (26-50) ----
{t:"The SI unit of energy is", o:["Joule","Newton","Watt","Pascal"], c:0, e:"Energy is measured in joules (J), same unit as work."},
{t:"The dimensional formula of acceleration is", o:["[LT⁻²]","[LT⁻¹]","[L]","[T⁻²]"], c:0, e:"Acceleration = velocity/time → [LT⁻¹]/[T] = [LT⁻²]."},
{t:"A car accelerates uniformly from rest to 20 m/s in 4 s. Its acceleration is", o:["5 m/s²","4 m/s²","80 m/s²","16 m/s²"], c:0, e:"a = Δv/t = (20-0)/4 = 5 m/s²."},
{t:"Linear momentum is the product of", o:["mass and velocity","mass and acceleration","mass and displacement","force and time"], c:0, e:"Momentum p = mv, i.e., mass times velocity."},
{t:"The SI unit of momentum is", o:["kg·m/s","kg·m/s²","Newton","Joule"], c:0, e:"Momentum = mass × velocity → kg × m/s = kg·m/s."},
{t:"The work done by a force when the displacement is zero is", o:["zero","maximum","infinite","negative"], c:0, e:"W = F·d; if displacement d = 0, work done is zero."},
{t:"The potential energy of a body of mass m at height h is", o:["mgh","½mv²","mg","mh"], c:0, e:"Gravitational potential energy formula: PE = mgh."},
{t:"One horsepower is approximately equal to", o:["746 W","100 W","1000 W","550 W"], c:0, e:"Standard conversion: 1 hp ≈ 746 W."},
{t:"The value of the universal gravitational constant G is approximately", o:["6.67×10⁻¹¹","9.8","6.022×10²³","1.6×10⁻¹⁹"], c:0, e:"G ≈ 6.67×10⁻¹¹ N·m²/kg² (standard constant in Newton's law of gravitation)."},
{t:"The weight of a body is zero at the", o:["centre of the earth","surface of the earth","poles","equator"], c:0, e:"At the earth's centre, gravitational pull is symmetric in all directions, so net effective weight is zero."},
{t:"The time period of a geostationary satellite is about", o:["24 hours","1 hour","12 hours","365 days"], c:0, e:"A geostationary satellite matches Earth's rotation period: ~24 hours."},
{t:"If the period of an oscillation is 0.5 s, its frequency is", o:["2 Hz","0.5 Hz","4 Hz","1 Hz"], c:0, e:"Frequency f = 1/T = 1/0.5 = 2 Hz."},
{t:"Sound cannot travel through", o:["vacuum","air","water","solids"], c:0, e:"Sound is a mechanical wave and needs a medium — it cannot travel through vacuum."},
{t:"An echo is produced due to the ______ of sound.", o:["reflection","refraction","diffraction","absorption"], c:0, e:"An echo occurs when sound waves reflect off a distant surface back to the listener."},
{t:"For a wave, the product of wavelength and frequency gives its", o:["velocity","acceleration","amplitude","period"], c:0, e:"Wave equation: v = fλ (velocity = frequency × wavelength)."},
{t:"The focal length of a plane mirror is", o:["infinity","zero","positive and finite","negative and finite"], c:0, e:"A plane mirror has zero curvature, so its focal length is infinite."},
{t:"A shaving mirror is usually a", o:["concave mirror","convex mirror","plane mirror","cylindrical mirror"], c:0, e:"A concave mirror produces a magnified upright image when the object is close — ideal for shaving."},
{t:"The SI unit of resistance measures", o:["resistance","current","voltage","power"], c:0, e:"Resistance itself is measured in ohms (Ω)."},
{t:"Electric power is given by", o:["VI","V/I","I/V","V + I"], c:0, e:"Electric power formula: P = VI (voltage × current)."},
{t:"Two 3 Ω resistors connected in series give an equivalent resistance of", o:["6 Ω","1.5 Ω","3 Ω","9 Ω"], c:0, e:"In series, resistances add: R = 3 + 3 = 6 Ω."},
{t:"The mass of an electron is approximately", o:["9.1×10⁻³¹ kg","1.6×10⁻¹⁹ kg","1.67×10⁻²⁷ kg","6.6×10⁻³⁴ kg"], c:0, e:"Electron mass ≈ 9.1×10⁻³¹ kg (1.6×10⁻¹⁹ C is its charge, not mass)."},
{t:"The SI unit of radioactivity is the", o:["Becquerel","Newton","Joule","Hertz"], c:0, e:"Radioactivity (decay rate) is measured in becquerels (Bq)."},
{t:"In a p-n junction diode, current flows easily in", o:["forward bias","reverse bias","both biases equally","neither bias"], c:0, e:"A diode conducts easily under forward bias and blocks current under reverse bias."},
{t:"The value of Planck's constant is approximately", o:["6.63×10⁻³⁴ J·s","1.6×10⁻¹⁹ J·s","3×10⁸ J·s","9.8 J·s"], c:0, e:"Planck's constant h ≈ 6.63×10⁻³⁴ J·s."},
{t:"A body of mass 2 kg moving at 3 m/s has a kinetic energy of", o:["9 J","6 J","18 J","3 J"], c:0, e:"KE = ½mv² = ½(2)(3²) = ½(2)(9) = 9 J."},
// ---- Chemistry (51-75) ----
{t:"The mass number of an atom is equal to the number of", o:["protons and neutrons","protons only","neutrons only","protons and electrons"], c:0, e:"Mass number A = number of protons + number of neutrons."},
{t:"The element with atomic number 6 is", o:["Carbon","Oxygen","Nitrogen","Hydrogen"], c:0, e:"Atomic number 6 corresponds to Carbon (6 protons)."},
{t:"The valency of oxygen is", o:["2","1","3","4"], c:0, e:"Oxygen has 6 valence electrons and needs 2 more to complete its octet, so valency = 2."},
{t:"Noble gases belong to group", o:["18","1","17","2"], c:0, e:"Noble gases (He, Ne, Ar...) occupy Group 18 of the periodic table."},
{t:"The lightest element is", o:["Hydrogen","Helium","Lithium","Oxygen"], c:0, e:"Hydrogen (atomic mass ≈1) is the lightest element in the periodic table."},
{t:"The number of groups in the modern periodic table is", o:["18","8","7","9"], c:0, e:"The modern periodic table has 18 groups (columns)."},
{t:"The chemical formula of common salt is", o:["NaCl","KCl","CaCl2","NaOH"], c:0, e:"Common salt (table salt) is sodium chloride, NaCl."},
{t:"The bond present in a chlorine molecule (Cl₂) is", o:["covalent","ionic","metallic","hydrogen"], c:0, e:"Two Cl atoms share an electron pair to form a covalent bond in Cl₂."},
{t:"The chemical formula of ammonia is", o:["NH3","NH4","N2H4","NO2"], c:0, e:"Ammonia's formula is NH₃ (1 nitrogen + 3 hydrogens)."},
{t:"One mole of any substance contains", o:["6.022×10²³ particles","3×10⁸ particles","1 particle","100 particles"], c:0, e:"By definition, 1 mole = Avogadro's number of particles = 6.022×10²³."},
{t:"The molar mass of carbon dioxide (CO₂) is", o:["44 g/mol","28 g/mol","12 g/mol","32 g/mol"], c:0, e:"CO₂ = 12 + 2(16) = 44 g/mol."},
{t:"The number of moles in 44 g of CO₂ is", o:["1","2","44","0.5"], c:0, e:"Moles = mass/molar mass = 44/44 = 1."},
{t:"The pH of pure water is", o:["7","1","14","0"], c:0, e:"Pure water is neutral with pH = 7."},
{t:"Bases turn red litmus", o:["blue","red","green","colourless"], c:0, e:"Bases turn red litmus paper blue (and blue litmus stays blue)."},
{t:"Reduction is defined as the", o:["gain of electrons","loss of electrons","sharing of electrons","none of these"], c:0, e:"Reduction = gain of electrons (remember: OIL RIG)."},
{t:"The rate of a chemical reaction generally ______ with an increase in temperature.", o:["increases","decreases","does not change","stops"], c:0, e:"Higher temperature gives molecules more kinetic energy, increasing reaction rate."},
{t:"Boyle's law states that at constant temperature", o:["PV = constant","P/V = constant","V/T = constant","PT = constant"], c:0, e:"Boyle's law: at constant T, pressure and volume are inversely proportional, so PV = constant."},
{t:"Standard temperature and pressure (STP) refers to", o:["0 °C and 1 atm","25 °C and 1 atm","100 °C and 1 atm","0 °C and 2 atm"], c:0, e:"STP is conventionally defined as 0 °C (273 K) and 1 atm pressure."},
{t:"Quicklime is chemically", o:["CaO","Ca(OH)2","CaCO3","CaCl2"], c:0, e:"Quicklime is calcium oxide, CaO."},
{t:"Combustion is an example of a(n) ______ reaction.", o:["oxidation","reduction","double displacement","neutralisation"], c:0, e:"Combustion involves a substance reacting with oxygen — a form of oxidation."},
{t:"The number of carbon atoms in an ethane molecule is", o:["2","1","3","4"], c:0, e:"Ethane's formula is C₂H₆ — it has 2 carbon atoms."},
{t:"The general formula of an alkene is", o:["CnH2n","CnH2n+2","CnH2n-2","CnHn"], c:0, e:"Unsaturated alkenes (one double bond) follow CₙH₂ₙ (e.g., ethene C₂H₄)."},
{t:"The functional group of a carboxylic acid is", o:["-COOH","-OH","-CHO","-CO-"], c:0, e:"Carboxylic acids are defined by the carboxyl group, -COOH."},
{t:"Fermentation of sugar produces", o:["ethanol","methanol","acetic acid","methane"], c:0, e:"Fermentation of sugars by yeast produces ethanol (and CO₂)."},
{t:"Natural rubber is a polymer of", o:["isoprene","ethene","vinyl chloride","styrene"], c:0, e:"Natural rubber is a polymer of isoprene units."},
// ---- English (76-90) ----
{t:'Choose the word nearest in meaning to "happy".', o:["sad","joyful","angry","tired"], c:1, e:'"Happy" and "joyful" both express a positive/pleased state.'},
{t:'Choose the word opposite in meaning to "victory".', o:["win","defeat","success","triumph"], c:1, e:'"Victory" (winning) is opposite to "defeat".'},
{t:"Fill in the blank: They ______ playing football now.", o:["is","am","are","be"], c:2, e:'Plural subject "They" with present continuous ("now") needs "are".'},
{t:"Fill in the blank: I have lived here ______ ten years.", o:["since","for","from","at"], c:1, e:'"For" is used with a duration of time ("ten years"); "since" is used with a starting point.'},
{t:'The correct plural of "tooth" is', o:["tooths","teeth","teeths","tooth"], c:1, e:'"Tooth" has the irregular plural "teeth".'},
{t:'Change into passive voice: "She sings a song."', o:["A song is sung by her","A song was sung by her","A song sang by her","She is sung a song"], c:0, e:"Present simple active → present simple passive: 'sings' becomes 'is sung by'."},
{t:"Fill in the blank: Each of the students ______ a book.", o:["has","have","were","are"], c:0, e:'"Each" is singular, so it takes the singular verb "has".'},
{t:"Choose the correctly spelt word.", o:["definitely","definately","definitly","defenitely"], c:0, e:'The correct spelling is "definitely" (common misspelling trap — no "a").'},
{t:'The idiom "once in a blue moon" means', o:["rarely","often","never","always"], c:0, e:'"Once in a blue moon" idiomatically means very rarely/infrequently.'},
{t:"Fill in the blank with the correct article: ______ university.", o:["a","an","the","no article"], c:0, e:'"University" starts with a consonant sound (/j/, like "yoo-"), so it takes "a", not "an".'},
{t:'The comparative form of "bad" is', o:["badder","worse","worst","more bad"], c:1, e:'"Bad" is irregular: bad → worse (comparative) → worst (superlative).'},
{t:"Fill in the blank: He is good ______ mathematics.", o:["at","in","on","for"], c:0, e:'The fixed idiomatic pairing is "good at" (a subject/skill).'},
{t:'Choose the word opposite in meaning to "expand".', o:["grow","contract","enlarge","extend"], c:1, e:'"Expand" (to grow larger) is opposite to "contract" (to shrink).'},
{t:'Choose the word nearest in meaning to "difficult".', o:["easy","hard","simple","light"], c:1, e:'"Difficult" and "hard" both mean not easy to do.'},
{t:"Choose the grammatically correct sentence.", o:["He is taller than me.","He is more tall than me.","He is tallest than me.","He taller than me."], c:0, e:'"Taller" is the correct one-word comparative; "more tall" and "tallest than" are incorrect forms.'},
// ---- Computer (91-100) ----
{t:"The permanent memory of a computer is", o:["RAM","ROM","Cache","Register"], c:1, e:"ROM (Read-Only Memory) is non-volatile and retains data permanently, even without power."},
{t:"ROM stands for", o:["Read Only Memory","Random Only Memory","Read Open Memory","Rapid Only Memory"], c:0, e:"ROM = Read Only Memory."},
{t:"One kilobyte (KB) is equal to", o:["1000 bytes","1024 bytes","8 bytes","512 bytes"], c:1, e:"In binary computing terms, 1 KB = 1024 bytes (2¹⁰)."},
{t:"The binary equivalent of the decimal number 8 is", o:["1000","1010","1100","111"], c:0, e:"8 = 2³ → binary 1000."},
{t:"Which of the following is an output device?", o:["Keyboard","Mouse","Printer","Scanner"], c:2, e:"A printer produces output from the computer; keyboard/mouse/scanner are input devices."},
{t:"HTTP stands for", o:["HyperText Transfer Protocol","High Text Transfer Protocol","HyperText Transmission Protocol","Hyper Transfer Text Protocol"], c:0, e:"HTTP = HyperText Transfer Protocol, used for web communication."},
{t:"MS Excel is mainly used for", o:["word processing","spreadsheets","presentations","painting"], c:1, e:"MS Excel is spreadsheet software for calculations and data organization."},
{t:"The full form of USB is", o:["Universal Serial Bus","Unique Serial Bus","Universal System Bus","United Serial Bus"], c:0, e:"USB = Universal Serial Bus."},
{t:"The decimal equivalent of the binary number 1111 is", o:["15","16","14","8"], c:0, e:"1111₂ = 8+4+2+1 = 15."},
{t:"The smallest unit of data in a computer is a", o:["bit","byte","nibble","word"], c:0, e:"A bit (binary digit, 0 or 1) is the smallest unit of data."},
],

3: [
// ---- Mathematics (1-25) ----
{t:"If n(A) = 3 and n(B) = 2, then n(A × B) is", o:["6","5","9","8"], c:0, e:"n(A×B) = n(A) × n(B) = 3 × 2 = 6."},
{t:"The value of i⁻¹ is", o:["i","-i","1","-1"], c:1, e:"i⁻¹ = 1/i = (1·i)/(i·i) = i/i² = i/(-1) = -i."},
{t:"The product of the roots of x² + x - 6 = 0 is", o:["-6","6","1","-1"], c:0, e:"Product of roots = c/a = -6/1 = -6."},
{t:"The sum of the roots of x² - 6x + 8 = 0 is", o:["6","8","-6","2"], c:0, e:"Sum of roots = -b/a = -(-6)/1 = 6."},
{t:"The domain of the function f(x) = 1/(x - 2) is", o:["all real numbers except 2","all real numbers","x > 2","x ≠ 0"], c:0, e:"The denominator cannot be zero, so x ≠ 2."},
{t:"The value of (1 + i)² is", o:["2i","1 + i","2","0"], c:0, e:"(1+i)² = 1 + 2i + i² = 1 + 2i - 1 = 2i."},
{t:"The 7th term of the AP 5, 8, 11, ... is", o:["23","26","20","29"], c:0, e:"aₙ = a+(n-1)d = 5 + 6(3) = 23."},
{t:"The sum of the first 10 odd natural numbers (1 + 3 + ... + 19) is", o:["100","90","110","81"], c:0, e:"Sum of first n odd numbers = n². Here n=10 → 10² = 100."},
{t:"The 4th term of the GP 2, 6, 18, ... is", o:["54","162","18","48"], c:0, e:"r = 3, a₄ = a·r³ = 2·27 = 54."},
{t:"The sum to infinity of 1 - 1/2 + 1/4 - ... is", o:["2/3","1/2","3/2","1"], c:0, e:"Here r = -1/2, S∞ = a/(1-r) = 1/(1+1/2) = 1/(3/2) = 2/3."},
{t:"The value of sin²θ + cos²θ is", o:["1","0","2","sin 2θ"], c:0, e:"Fundamental Pythagorean identity: sin²θ + cos²θ = 1 for every θ."},
{t:"The value of log₅ 125 is", o:["3","5","25","2"], c:0, e:"5³ = 125, so log₅ 125 = 3."},
{t:"If log₁₀ x = 3, then x is", o:["1000","100","300","30"], c:0, e:"log₁₀ x = 3 means x = 10³ = 1000."},
{t:"The determinant of [[2, 1], [1, 2]] is", o:["3","4","5","1"], c:0, e:"det = (2)(2) - (1)(1) = 4 - 1 = 3."},
{t:"The value of tan 60° is", o:["√3","1/√3","1","3"], c:0, e:"Standard value: tan 60° = √3."},
{t:"The value of sin 30° + cos 60° is", o:["1/2","1","3/2","0"], c:1, e:"sin30° = 1/2, cos60° = 1/2; sum = 1/2 + 1/2 = 1."},
{t:"If tanθ = 1 and θ is acute, then θ is", o:["30°","45°","60°","90°"], c:1, e:"tan 45° = 1, so θ = 45°."},
{t:"The value of cosec 30° is", o:["2","1","√2","1/2"], c:0, e:"cosec30° = 1/sin30° = 1/(1/2) = 2."},
{t:"The distance between the points (2, 3) and (2, 7) is", o:["4","√4","5","10"], c:0, e:"Same x-coordinate, so distance = |7-3| = 4."},
{t:"The slope of the y-axis is", o:["0","1","undefined","-1"], c:2, e:"The y-axis is vertical; a vertical line has an undefined slope."},
{t:"The circle x² + y² = 100 has a radius of", o:["10","100","√10","50"], c:0, e:"r² = 100, so r = 10."},
{t:"The derivative of 5x³ with respect to x is", o:["15x²","5x²","15x³","3x²"], c:0, e:"d/dx(5x³) = 5·3x² = 15x²."},
{t:"The value of ∫ 2x dx is", o:["x² + c","2x² + c","x + c","2 + c"], c:0, e:"∫2x dx = 2·(x²/2) + c = x² + c."},
{t:"The value of lim(x→∞) 1/x is", o:["0","1","∞","undefined"], c:0, e:"As x grows infinitely large, 1/x approaches 0."},
{t:"The function y = x² - 4x + 5 has a minimum at x =", o:["2","-2","4","0"], c:0, e:"dy/dx = 2x - 4 = 0 → x = 2; y'' = 2 > 0 confirms a minimum."},
// ---- Physics (26-50) ----
{t:"The SI unit of power is", o:["Watt","Joule","Newton","Volt"], c:0, e:"Power (energy per time) is measured in watts (W)."},
{t:"The dimensional formula of force is", o:["[MLT⁻²]","[MLT⁻¹]","[ML²T⁻²]","[LT⁻²]"], c:0, e:"F = ma → [M][LT⁻²] = [MLT⁻²]."},
{t:"The distance covered by a body in time t moving with uniform velocity v is", o:["vt","½vt","v/t","v²t"], c:0, e:"For uniform velocity, distance = velocity × time = vt."},
{t:"Newton's first law of motion is also called the law of", o:["inertia","action and reaction","gravitation","momentum"], c:0, e:"Newton's first law describes objects resisting changes in motion — the law of inertia."},
{t:"The SI unit of pressure is", o:["Pascal","Newton","Joule","Watt"], c:0, e:"Pressure (force per area) is measured in pascals (Pa)."},
{t:"Work done is defined as", o:["force × displacement","force ÷ displacement","force + displacement","force × time"], c:0, e:"Work = Force × displacement (in the direction of force)."},
{t:"One joule is equal to", o:["one newton-metre","one newton per metre","one newton-second","one kilogram-metre"], c:0, e:"By definition, 1 joule = 1 newton × 1 metre (N·m)."},
{t:"The energy possessed by a body due to its motion is called", o:["kinetic energy","potential energy","chemical energy","nuclear energy"], c:0, e:"Kinetic energy is the energy of motion, KE = ½mv²."},
{t:"The value of acceleration due to gravity is maximum at the", o:["poles","equator","centre","sea level"], c:0, e:"Earth bulges at the equator, so poles (closer to Earth's centre) have slightly higher g."},
{t:"Weight of a body is given by", o:["mg","ma","m/g","mv"], c:0, e:"Weight = mass × acceleration due to gravity = mg."},
{t:"If the value of g on the moon is 1/6 that of earth, a body weighing 60 N on earth will weigh ______ on the moon.", o:["10 N","60 N","360 N","6 N"], c:0, e:"Weight on moon = 60 × (1/6) = 10 N."},
{t:"In SHM, the restoring force is proportional to the", o:["displacement","velocity","acceleration","time"], c:0, e:"Simple Harmonic Motion is defined by a restoring force proportional to displacement (F = -kx)."},
{t:"Ultrasonic sound has a frequency", o:["above 20,000 Hz","below 20 Hz","between 20 and 20,000 Hz","equal to 0 Hz"], c:0, e:"Ultrasonic waves exceed the human hearing range, i.e., above 20,000 Hz."},
{t:"The reflection of sound from a distant surface causes a(n)", o:["echo","mirage","rainbow","tide"], c:0, e:"Sound reflecting off a distant surface and returning to the listener creates an echo."},
{t:"In vacuum, light travels at a speed of", o:["3×10⁸ m/s","340 m/s","1500 m/s","3×10⁶ m/s"], c:0, e:"Speed of light in vacuum, c = 3×10⁸ m/s."},
{t:"The image formed by a plane mirror is", o:["virtual and erect","real and inverted","real and erect","virtual and inverted"], c:0, e:"A plane mirror always forms a virtual, erect (same size) image."},
{t:"The power of a lens is measured in", o:["Dioptre","Watt","Lux","Candela"], c:0, e:"Lens power is measured in dioptres (D), the reciprocal of focal length in metres."},
{t:"A good conductor has ______ electrical resistance.", o:["low","high","infinite","negative"], c:0, e:"Good conductors offer very little resistance to current flow."},
{t:"The kilowatt-hour is a unit of", o:["energy","power","current","charge"], c:0, e:"kWh measures energy consumed (power × time), commonly used for electricity billing."},
{t:"Two 6 Ω resistors connected in parallel give an equivalent resistance of", o:["3 Ω","12 Ω","6 Ω","1.5 Ω"], c:0, e:"Parallel: 1/R = 1/6+1/6 = 2/6 → R = 3 Ω."},
{t:"The number of protons in a hydrogen atom is", o:["1","0","2","7"], c:0, e:"Hydrogen (atomic number 1) has exactly 1 proton."},
{t:"An alpha particle is", o:["a helium nucleus","an electron","a photon","a proton"], c:0, e:"An alpha particle is a helium nucleus: 2 protons + 2 neutrons."},
{t:"An LED (Light Emitting Diode) is a device that", o:["emits light","stores charge","resists current","amplifies signals"], c:0, e:"An LED converts electrical energy into light when forward biased."},
{t:"Einstein's photoelectric equation is based on the concept of", o:["photons","sound waves","heat","gravity"], c:0, e:"Einstein explained the photoelectric effect using quantized packets of light — photons."},
{t:"A force of 10 N acts on a mass of 2 kg. The acceleration produced is", o:["5 m/s²","20 m/s²","2 m/s²","0.2 m/s²"], c:0, e:"a = F/m = 10/2 = 5 m/s²."},
// ---- Chemistry (51-75) ----
{t:"The number of neutrons in an atom is given by", o:["mass number − atomic number","mass number + atomic number","atomic number − mass number","atomic number"], c:0, e:"Neutrons = Mass number (protons+neutrons) − Atomic number (protons)."},
{t:"The element with the symbol Na is", o:["Sodium","Nitrogen","Nickel","Neon"], c:0, e:'"Na" (from Latin "Natrium") is the symbol for Sodium.'},
{t:"The valency of hydrogen is", o:["1","2","3","0"], c:0, e:"Hydrogen has 1 electron and forms 1 bond, so its valency is 1."},
{t:"Halogens belong to group", o:["17","18","1","2"], c:0, e:"Halogens (F, Cl, Br, I...) occupy Group 17."},
{t:"The most abundant gas in the earth's atmosphere is", o:["Nitrogen","Oxygen","Carbon dioxide","Argon"], c:0, e:"Nitrogen makes up about 78% of Earth's atmosphere, the most abundant gas."},
{t:"The horizontal rows of the periodic table are called", o:["periods","groups","families","blocks"], c:0, e:"Horizontal rows are periods; vertical columns are groups."},
{t:"The chemical formula of water is", o:["H2O","H2O2","HO","OH"], c:0, e:"Water's formula is H₂O — 2 hydrogens, 1 oxygen."},
{t:"Sodium chloride is held together by ______ bonding.", o:["ionic","covalent","metallic","hydrogen"], c:0, e:"NaCl forms via electron transfer from Na to Cl, creating an ionic bond."},
{t:"The chemical formula of sulphuric acid is", o:["H2SO4","HCl","HNO3","H2SO3"], c:0, e:"Sulphuric acid's formula is H₂SO₄."},
{t:"The molar mass of sodium hydroxide (NaOH) is", o:["40 g/mol","23 g/mol","58 g/mol","56 g/mol"], c:0, e:"NaOH = 23 + 16 + 1 = 40 g/mol."},
{t:"The molar mass of an oxygen molecule (O₂) is", o:["32 g/mol","16 g/mol","8 g/mol","48 g/mol"], c:0, e:"O₂ = 2 × 16 = 32 g/mol."},
{t:"The number of moles in 64 g of O₂ is", o:["2","1","4","0.5"], c:0, e:"Moles = mass/molar mass = 64/32 = 2."},
{t:"A solution with pH 2 is", o:["acidic","basic","neutral","amphoteric"], c:0, e:"pH < 7 indicates an acidic solution; pH 2 is strongly acidic."},
{t:"Litmus is an example of a natural", o:["indicator","catalyst","salt","base"], c:0, e:"Litmus is a natural pH indicator, extracted from lichens."},
{t:"The loss of hydrogen in a reaction is called", o:["oxidation","reduction","neutralisation","hydrolysis"], c:0, e:"In classical terms, losing hydrogen (or oxygen gain) defines oxidation."},
{t:"Enzymes act as biological", o:["catalysts","acids","bases","salts"], c:0, e:"Enzymes speed up biochemical reactions without being consumed — biological catalysts."},
{t:"Charles's law describes the relationship between", o:["volume and temperature","pressure and volume","pressure and temperature","moles and volume"], c:0, e:"Charles's law: at constant pressure, volume is directly proportional to temperature."},
{t:"The molar volume of a gas at STP is", o:["22.4 L","24 L","11.2 L","1 L"], c:0, e:"At STP, 1 mole of any ideal gas occupies 22.4 L."},
{t:"Baking soda is chemically", o:["NaHCO3","Na2CO3","NaOH","NaCl"], c:0, e:"Baking soda is sodium bicarbonate, NaHCO₃."},
{t:"Photosynthesis converts carbon dioxide and water mainly into", o:["glucose","ethanol","methane","starch only"], c:0, e:"Photosynthesis produces glucose (C₆H₁₂O₆) and oxygen from CO₂ and water."},
{t:"The number of hydrogen atoms in a methane molecule is", o:["4","3","2","1"], c:0, e:"Methane's formula CH₄ has 4 hydrogen atoms."},
{t:"The general formula of an alkyne is", o:["CnH2n-2","CnH2n","CnH2n+2","CnHn"], c:0, e:"Alkynes (triple bond) follow CₙH₂ₙ₋₂ (e.g., ethyne C₂H₂)."},
{t:"The functional group present in an aldehyde is", o:["-CHO","-OH","-COOH","-CO-"], c:0, e:"Aldehydes are characterised by the -CHO (carbonyl-hydrogen) group."},
{t:"Marble is chemically", o:["calcium carbonate","calcium oxide","calcium hydroxide","calcium sulphate"], c:0, e:"Marble is a form of calcium carbonate, CaCO₃."},
{t:"PVC is a polymer of", o:["vinyl chloride","ethene","styrene","isoprene"], c:0, e:"PVC (polyvinyl chloride) is made by polymerising vinyl chloride monomers."},
// ---- English (76-90) ----
{t:'Choose the word nearest in meaning to "rapid".', o:["slow","quick","late","dull"], c:1, e:'"Rapid" means fast — nearest synonym is "quick".'},
{t:'Choose the word opposite in meaning to "friend".', o:["pal","enemy","mate","ally"], c:1, e:'"Friend" is opposite to "enemy".'},
{t:"Fill in the blank: The sun ______ in the east.", o:["rise","rises","rising","rose"], c:1, e:'General/habitual truth with singular subject "sun" needs "rises".'},
{t:"Fill in the blank: He is fond ______ music.", o:["of","for","with","to"], c:0, e:'The fixed idiomatic pairing is "fond of".'},
{t:'The correct plural of "man" is', o:["mans","men","mens","man"], c:1, e:'"Man" has the irregular plural "men".'},
{t:'Change into passive voice: "They built a house."', o:["A house was built by them","A house is built by them","A house built by them","They were built a house"], c:0, e:"Past simple active → past simple passive: 'built' becomes 'was built by'."},
{t:"Fill in the blank: Ram, as well as his friends, ______ present.", o:["is","are","were","have"], c:0, e:'"As well as" doesn\'t make the subject plural — the verb agrees with "Ram" (singular): "is".'},
{t:"Choose the correctly spelt word.", o:["occassion","occasion","ocassion","occassiion"], c:1, e:'The correct spelling is "occasion" — double "c", single "s".'},
{t:'The idiom "a piece of cake" means something that is', o:["very easy","delicious","very difficult","expensive"], c:0, e:'"A piece of cake" idiomatically means a task that is very easy.'},
{t:"Fill in the blank with the correct article: ______ European.", o:["a","an","the","no article"], c:0, e:'"European" starts with a consonant sound (/j/, "yoo-"), so it takes "a", not "an".'},
{t:'The superlative form of "little" is', o:["littlest","least","less","littler"], c:0, e:'"Little" (uncountable, meaning small in quantity/size, referring to amount) → littlest is the standard superlative used here.'},
{t:"Fill in the blank: She is married ______ a doctor.", o:["to","with","from","at"], c:0, e:'The fixed idiomatic pairing is "married to".'},
{t:'Choose the word opposite in meaning to "increase".', o:["rise","decrease","grow","expand"], c:1, e:'"Increase" (to grow) is opposite to "decrease" (to reduce).'},
{t:'Choose the word nearest in meaning to "big".', o:["small","large","tiny","little"], c:1, e:'"Big" and "large" both mean of considerable size.'},
{t:"Choose the grammatically correct sentence.", o:["I don't have any money.","I don't have no money.","I not have any money.","I haven't no money."], c:0, e:'Standard English avoids double negatives; "don\'t have any" is correct (not "don\'t have no").'},
// ---- Computer (91-100) ----
{t:"Which of the following converts source code into machine code?", o:["Compiler","Editor","Loader","Debugger"], c:0, e:"A compiler translates high-level source code into machine code."},
{t:"GUI stands for", o:["Graphical User Interface","General User Interface","Graphical Unit Interface","Global User Interface"], c:0, e:"GUI = Graphical User Interface."},
{t:"One megabyte (MB) is equal to", o:["1024 KB","1000 KB","1024 bytes","8 KB"], c:0, e:"In binary terms, 1 MB = 1024 KB (2¹⁰ KB)."},
{t:"The binary equivalent of the decimal number 3 is", o:["11","10","100","111"], c:0, e:"3 = 2+1 → binary 11."},
{t:"The CPU consists of the ALU and the", o:["Control Unit","ROM","Monitor","Keyboard"], c:0, e:"The CPU's two main parts are the ALU (Arithmetic Logic Unit) and the Control Unit."},
{t:"LAN stands for", o:["Local Area Network","Large Area Network","Long Area Network","Local Access Network"], c:0, e:"LAN = Local Area Network, a network within a small geographic area."},
{t:"MS PowerPoint is mainly used to create", o:["presentations","spreadsheets","databases","program code"], c:0, e:"MS PowerPoint is presentation software for slideshows."},
{t:"The full form of PDF is", o:["Portable Document Format","Personal Document Format","Portable Data Format","Print Document Format"], c:0, e:"PDF = Portable Document Format."},
{t:"The decimal equivalent of the binary number 100 is", o:["4","2","8","6"], c:0, e:"100₂ = 1×4 + 0×2 + 0×1 = 4."},
{t:"A device that connects a computer to the internet is a", o:["Modem","Monitor","Printer","Scanner"], c:0, e:"A modem (modulator-demodulator) connects a computer to an internet connection."},
],

4: [
// ---- Mathematics (1-25) ----
{t:"The number of elements in the power set of a set with 3 elements is", o:["8","6","3","9"], c:0, e:"Power set size = 2ⁿ = 2³ = 8."},
{t:"The value of i² is", o:["-1","1","i","-i"], c:0, e:"By definition, i = √-1, so i² = -1."},
{t:"If one root of x² - 5x + k = 0 is 2, then the value of k is", o:["6","4","10","-6"], c:0, e:"Substitute x=2: 4 - 10 + k = 0 → k = 6."},
{t:"The product of the roots of x² + 7x + 10 = 0 is", o:["10","-7","7","-10"], c:0, e:"Product of roots = c/a = 10/1 = 10."},
{t:"If A and B are disjoint sets with n(A) = 4 and n(B) = 3, then n(A ∪ B) is", o:["7","12","1","0"], c:0, e:"Disjoint sets share no elements, so n(A∪B) = 4 + 3 = 7."},
{t:"The value of 1/i is", o:["-i","i","1","-1"], c:0, e:"1/i = i/i² = i/(-1) = -i."},
{t:"The common difference of the AP 7, 10, 13, ... is", o:["3","7","10","17"], c:0, e:"d = second term − first term = 10 − 7 = 3."},
{t:"The sum of the first 5 terms of the AP 2, 4, 6, ... is", o:["30","20","25","40"], c:0, e:"Terms: 2+4+6+8+10 = 30."},
{t:"In a GP with first term 1 and common ratio 3, the sum of the first 3 terms is", o:["13","9","27","12"], c:0, e:"Terms: 1+3+9 = 13."},
{t:"The 6th term of the GP 5, 10, 20, ... is", o:["160","80","320","40"], c:0, e:"r=2, a₆ = a·r⁵ = 5·32 = 160."},
{t:"The equation of the straight line with slope 2 passing through the origin is", o:["y = 2x","y = x + 2","y = 2","x = 2"], c:0, e:"y = mx + c with m = 2 and c = 0 gives y = 2x."},
{t:"The value of log₁₀ 100 is", o:["2","10","100","1"], c:0, e:"10² = 100, so log₁₀ 100 = 2."},
{t:"The value of log₂ 1 is", o:["0","1","2","undefined"], c:0, e:"Any log of 1 (base > 0, ≠1) is 0, since base⁰ = 1."},
{t:"The determinant of [[0, 1], [1, 0]] is", o:["-1","1","0","2"], c:0, e:"det = (0)(0) - (1)(1) = -1."},
{t:"The value of cos 90° is", o:["0","1","1/2","undefined"], c:0, e:"Standard value: cos 90° = 0."},
{t:"The value of sin² 45° is", o:["1/2","1","√2/2","1/4"], c:0, e:"sin45° = 1/√2, so sin²45° = 1/2."},
{t:"If sinθ = 1 and 0° ≤ θ ≤ 90°, then θ is", o:["0°","30°","60°","90°"], c:3, e:"sin 90° = 1, and 90° lies in the given range."},
{t:"The value of sec 60° is", o:["2","1","1/2","√2"], c:0, e:"sec60° = 1/cos60° = 1/(1/2) = 2."},
{t:"The midpoint of the line joining (2, 4) and (6, 8) is", o:["(4, 6)","(8, 12)","(2, 2)","(3, 3)"], c:0, e:"Midpoint = ((2+6)/2, (4+8)/2) = (4, 6)."},
{t:"The slope of the line y = 3x + 2 is", o:["3","2","-3","1/3"], c:0, e:"In y = mx + c form, slope m = 3."},
{t:"The equation of a circle with centre at the origin and radius 3 is", o:["x² + y² = 9","x² + y² = 3","x² + y² = 6","x + y = 9"], c:0, e:"Circle formula x²+y²=r²; r=3 → x²+y²=9."},
{t:"The derivative of the constant 7 with respect to x is", o:["0","7","1","7x"], c:0, e:"The derivative of any constant is 0."},
{t:"The value of ∫ dx is", o:["x + c","1 + c","x²/2 + c","0"], c:0, e:"∫1 dx = x + c."},
{t:"The value of lim(x→3) (x + 2) is", o:["5","3","2","undefined"], c:0, e:"Direct substitution (continuous function): 3 + 2 = 5."},
{t:"The value of lim(x → ∞) (2x + 1)/(x + 3) is", o:["2","1","0","∞"], c:0, e:"∞/∞ form → L'Hospital (or divide through by x): 2/1 = 2."},
// ---- Physics (26-50) ----
{t:"The SI unit of frequency is", o:["Hertz","Watt","Newton","Joule"], c:0, e:"Frequency is measured in hertz (Hz)."},
{t:"The dimensional formula of work is", o:["[ML²T⁻²]","[MLT⁻²]","[MLT⁻¹]","[ML²T⁻¹]"], c:0, e:"Work = Force × distance = [MLT⁻²][L] = [ML²T⁻²]."},
{t:"A body at rest has a velocity of", o:["zero","positive value","negative value","infinite value"], c:0, e:"By definition, a body at rest is not moving, so its velocity is zero."},
{t:'The statement "to every action there is an equal and opposite reaction" is Newton\'s ______ law.', o:["third","first","second","law of gravitation"], c:0, e:"This is a direct statement of Newton's third law of motion."},
{t:"The SI unit of temperature is", o:["Kelvin","Celsius","Fahrenheit","Joule"], c:0, e:"The SI base unit of temperature is the kelvin (K)."},
{t:"If no external force acts on a moving body, it continues to move with", o:["constant velocity","increasing velocity","decreasing velocity","zero velocity"], c:0, e:"Newton's first law (inertia): no net force means no change in velocity."},
{t:"The SI unit of impulse is", o:["N·s","N/s","N·m","kg/s"], c:0, e:"Impulse = force × time = N·s (also equals change in momentum, kg·m/s)."},
{t:"A stretched bow possesses", o:["potential energy","kinetic energy","heat energy","sound energy"], c:0, e:"A stretched bow stores energy due to its deformed/stretched position — potential energy."},
{t:"The value of acceleration due to gravity ______ with increasing altitude.", o:["decreases","increases","remains constant","becomes zero"], c:0, e:"g decreases as you move farther from Earth's centre (higher altitude)."},
{t:"The weight of an object on the moon is ______ its weight on earth.", o:["less than","more than","equal to","zero times"], c:0, e:"Moon's gravity (~1/6th of Earth's) makes weight there less than on Earth."},
{t:"For a satellite revolving around the earth, the centripetal acceleration is directed", o:["towards the centre of the earth","away from the earth","along the tangent","equal to zero"], c:0, e:"Centripetal acceleration always points toward the centre of the circular path."},
{t:"The number of oscillations completed per second is called", o:["frequency","amplitude","wavelength","period"], c:0, e:"Frequency is defined as oscillations (cycles) completed per second."},
{t:"The audible range of frequency for a normal human is", o:["20 Hz to 20,000 Hz","0 Hz to 20 Hz","above 20,000 Hz","below 20 Hz"], c:0, e:"Human hearing range is approximately 20 Hz to 20,000 Hz."},
{t:"Bats navigate using", o:["ultrasonic waves","infrasonic waves","audible sound","radio waves"], c:0, e:"Bats use echolocation with ultrasonic waves (above human hearing range)."},
{t:"Light is a form of ______ wave.", o:["electromagnetic","mechanical","sound","matter"], c:0, e:"Light is an electromagnetic wave — it needs no medium to travel."},
{t:"A convex lens forms a real image when the object is placed", o:["beyond the focus","at the focus","between the focus and lens","at the optical centre"], c:0, e:"A convex lens forms a real image when the object is placed beyond its focal point."},
{t:"The SI unit of electric charge is", o:["Coulomb","Ampere","Volt","Ohm"], c:0, e:"Electric charge is measured in coulombs (C)."},
{t:"Conventional electric current flows from the", o:["positive to negative terminal","negative to positive terminal","both directions","no fixed direction"], c:0, e:"By convention, current direction is taken from positive to negative terminal (opposite to actual electron flow)."},
{t:"The heat produced in a resistor is given by", o:["I²Rt","IRt","IR²t","I/Rt"], c:0, e:"Joule's law of heating: H = I²Rt."},
{t:"Three 3 Ω resistors connected in series give an equivalent resistance of", o:["9 Ω","1 Ω","3 Ω","6 Ω"], c:0, e:"Series resistances add: 3+3+3 = 9 Ω."},
{t:"Isotopes of an element have the same number of", o:["protons","neutrons","nucleons","mass units"], c:0, e:"Isotopes share the same proton count (atomic number) but differ in neutrons."},
{t:"Gamma rays carry", o:["no charge","positive charge","negative charge","variable charge"], c:0, e:"Gamma rays are high-energy electromagnetic radiation, carrying no electric charge."},
{t:"A transistor is mainly used to", o:["amplify signals","store charge","resist current","rectify current"], c:0, e:"Transistors are primarily used as amplifiers (and switches) in electronic circuits."},
{t:"The energy of a photon is given by", o:["hf","h/f","hf²","f/h"], c:0, e:"Planck's relation: photon energy E = hf (Planck's constant × frequency)."},
{t:"A 100 W bulb used for 10 hours consumes energy equal to", o:["1 kWh","10 kWh","100 kWh","1000 kWh"], c:0, e:"Energy = Power × time = 100 W × 10 h = 1000 Wh = 1 kWh."},
// ---- Chemistry (51-75) ----
{t:"The central, dense part of an atom is called the", o:["nucleus","shell","orbit","electron cloud"], c:0, e:"The nucleus is the dense central core containing protons and neutrons."},
{t:"The chemical symbol of potassium is", o:["K","P","Po","Pt"], c:0, e:'"K" (from Latin "Kalium") is the symbol for Potassium.'},
{t:"The valency of carbon is", o:["4","2","3","1"], c:0, e:"Carbon has 4 valence electrons and forms 4 bonds, so its valency is 4."},
{t:"Alkaline earth metals belong to group", o:["2","1","17","18"], c:0, e:"Alkaline earth metals (Be, Mg, Ca...) occupy Group 2."},
{t:"The gas essential for respiration is", o:["Oxygen","Nitrogen","Carbon dioxide","Hydrogen"], c:0, e:"Oxygen is required by cells for aerobic respiration."},
{t:"The vertical columns of the periodic table are called", o:["groups","periods","blocks","shells"], c:0, e:"Vertical columns are groups; horizontal rows are periods."},
{t:"The chemical formula of methane is", o:["CH4","C2H6","CO2","CH3"], c:0, e:"Methane's formula is CH₄ — 1 carbon, 4 hydrogens."},
{t:"Diamond is an allotrope of", o:["carbon","silicon","sulphur","boron"], c:0, e:"Diamond and graphite are both allotropes (structural forms) of carbon."},
{t:"The chemical formula of nitric acid is", o:["HNO3","H2SO4","HCl","HNO2"], c:0, e:"Nitric acid's formula is HNO₃."},
{t:"The molar mass of calcium carbonate (CaCO3) is", o:["100 g/mol","56 g/mol","44 g/mol","74 g/mol"], c:0, e:"CaCO3 = 40 + 12 + 3(16) = 40+12+48 = 100 g/mol."},
{t:"The molar mass of sulphuric acid (H2SO4) is", o:["98 g/mol","49 g/mol","100 g/mol","80 g/mol"], c:0, e:"H2SO4 = 2(1) + 32 + 4(16) = 2+32+64 = 98 g/mol."},
{t:"One mole of carbon atoms has a mass of", o:["12 g","6 g","24 g","1 g"], c:0, e:"Carbon's molar mass is 12 g/mol, so one mole weighs 12 g."},
{t:"A neutral aqueous solution has a pH of", o:["7","0","14","1"], c:0, e:"Pure/neutral water has pH = 7."},
{t:"Phenolphthalein turns ______ in a basic solution.", o:["pink","colourless","blue","red"], c:0, e:"Phenolphthalein is colourless in acid/neutral solutions and turns pink in bases."},
{t:"The gain of hydrogen in a reaction is called", o:["reduction","oxidation","hydrolysis","neutralisation"], c:0, e:"Classically, gaining hydrogen (or losing oxygen) defines reduction."},
{t:"The rate of a chemical reaction depends on the", o:["concentration of reactants","colour of reactants","mass number","density only"], c:0, e:"Reaction rate depends on factors like concentration, temperature, and catalysts — concentration is key here."},
{t:"The ideal gas equation is", o:["PV = nRT","PV = RT","P = nRT","PVT = nR"], c:0, e:"The ideal gas law is PV = nRT (n = moles, R = gas constant, T = temperature)."},
{t:"At STP, 2 moles of a gas occupy a volume of", o:["44.8 L","22.4 L","11.2 L","2 L"], c:0, e:"1 mole = 22.4 L at STP, so 2 moles = 44.8 L."},
{t:"Washing soda is chemically", o:["Na2CO3·10H2O","NaHCO3","NaOH","NaCl"], c:0, e:"Washing soda is hydrated sodium carbonate, Na₂CO₃·10H₂O."},
{t:"Respiration in living organisms is a type of ______ reaction.", o:["oxidation","reduction","neutralisation","polymerisation"], c:0, e:"Respiration breaks down glucose using oxygen — an oxidation process."},
{t:"In an ethene molecule, the two carbon atoms are joined by a", o:["double bond","single bond","triple bond","no bond"], c:0, e:"Ethene (C2H4) has a carbon-carbon double bond, making it an alkene."},
{t:"Alkanes are ______ hydrocarbons.", o:["saturated","unsaturated","aromatic","cyclic only"], c:0, e:"Alkanes contain only single bonds, making them saturated hydrocarbons."},
{t:"The functional group present in a ketone is", o:["carbonyl (>C=O)","hydroxyl (-OH)","carboxyl (-COOH)","amino (-NH2)"], c:0, e:"Ketones are characterised by a carbonyl group (>C=O) attached to two carbon chains."},
{t:"Chalk is chemically", o:["calcium carbonate","calcium oxide","calcium sulphate","calcium hydroxide"], c:0, e:"Chalk, like marble and limestone, is calcium carbonate (CaCO₃)."},
{t:"Nylon is a ______ polymer.", o:["synthetic","natural","semi-natural","biological"], c:0, e:"Nylon is a man-made (synthetic) polyamide polymer."},
// ---- English (76-90) ----
{t:'Choose the word nearest in meaning to "clever".', o:["dull","intelligent","foolish","lazy"], c:1, e:'"Clever" means quick-witted — nearest synonym is "intelligent".'},
{t:'Choose the word opposite in meaning to "accept".', o:["take","reject","agree","receive"], c:1, e:'"Accept" is opposite to "reject".'},
{t:"Fill in the blank: Water ______ at 100 °C.", o:["boil","boils","boiling","boiled"], c:1, e:'General scientific fact with singular subject "Water" needs the -s form: "boils".'},
{t:"Fill in the blank: She is angry ______ me.", o:["with","for","to","on"], c:0, e:'The fixed idiomatic pairing is "angry with" (a person).'},
{t:'The correct plural of "leaf" is', o:["leafs","leaves","leafes","leaf"], c:1, e:'"Leaf" changes f→v before adding -es: "leaves".'},
{t:'Change into passive voice: "I eat an apple."', o:["An apple is eaten by me","An apple was eaten by me","An apple eats by me","I am eaten an apple"], c:0, e:"Present simple active → present simple passive: 'eat' becomes 'is eaten by'."},
{t:"Fill in the blank: Mathematics ______ my favourite subject.", o:["is","are","were","have"], c:0, e:'"Mathematics" (subject name) is treated as singular: "is".'},
{t:"Choose the correctly spelt word.", o:["seperate","separate","seperete","separete"], c:1, e:'The correct spelling is "separate" (common misspelling trap: remember "there\'s A RAT in sepARATe").'},
{t:'The idiom "to hit the nail on the head" means to', o:["be exactly right","build something","hurt someone","fail badly"], c:0, e:'"Hit the nail on the head" idiomatically means to describe or identify something exactly right.'},
{t:"Fill in the blank with the correct article: ______ hour.", o:["a","an","the","no article"], c:1, e:'"Hour" begins with a silent "h", so it starts with a vowel sound → "an hour".'},
{t:'The comparative form of "many" is', o:["manier","more","most","much"], c:1, e:'"Many" is irregular: many → more (comparative) → most (superlative).'},
{t:"Fill in the blank: You should not depend ______ others.", o:["on","at","in","for"], c:0, e:'The fixed idiomatic pairing is "depend on".'},
{t:'Choose the word opposite in meaning to "begin".', o:["start","end","commence","open"], c:1, e:'"Begin" (to start) is opposite to "end" (to finish).'},
{t:'Choose the word nearest in meaning to "beautiful".', o:["ugly","pretty","plain","dull"], c:1, e:'"Beautiful" and "pretty" both describe pleasing appearance.'},
{t:"Choose the grammatically correct sentence.", o:["She has been ill since Monday.","She is ill since Monday.","She has been for Monday.","She was ill since Monday."], c:0, e:'Present perfect continuous ("has been ill") correctly pairs with "since" + a starting point.'},
// ---- Computer (91-100) ----
{t:"Which of the following is system software?", o:["MS Word","Operating System","Photoshop","Chrome"], c:1, e:"An Operating System manages hardware/software resources — it's system software; the others are application software."},
{t:"IP stands for", o:["Internet Protocol","Internal Protocol","Internet Program","Interface Protocol"], c:0, e:"IP = Internet Protocol, used for addressing and routing data."},
{t:"One gigabyte (GB) is equal to", o:["1024 MB","1000 MB","1024 KB","8 MB"], c:0, e:"In binary terms, 1 GB = 1024 MB (2¹⁰ MB)."},
{t:"The binary equivalent of the decimal number 6 is", o:["110","101","100","111"], c:0, e:"6 = 4+2 → binary 110."},
{t:"Which language does a computer directly understand?", o:["Machine language","English","C language","Python"], c:0, e:"Computers directly execute machine language (binary instructions); other languages need translation."},
{t:"WAN stands for", o:["Wide Area Network","Wireless Area Network","Web Area Network","Wide Access Network"], c:0, e:"WAN = Wide Area Network, spanning large geographic areas."},
{t:"The keyboard shortcut used to copy selected text is", o:["Ctrl + C","Ctrl + V","Ctrl + X","Ctrl + P"], c:0, e:"Ctrl+C copies; Ctrl+V pastes; Ctrl+X cuts; Ctrl+P prints."},
{t:"The full form of CD is", o:["Compact Disc","Computer Disc","Compact Data","Central Disc"], c:0, e:"CD = Compact Disc."},
{t:"The decimal equivalent of the binary number 1001 is", o:["9","8","10","11"], c:0, e:"1001₂ = 8+0+0+1 = 9."},
{t:"The first general-purpose electronic computer was", o:["ENIAC","UNIVAC","IBM 701","Apple I"], c:0, e:"ENIAC (1945) is widely regarded as the first general-purpose electronic computer."},
],
// ===== OFFICIAL PAPER: TU IOST B.Sc. CSIT Entrance Model Question =====
// Verbatim from the IOST-published model question (Full Marks 100, Time 2:00 hrs).
// Pattern: Mathematics 25, Physics 25, Chemistry 25, English 15, Computer Related GK 10.
// The published paper carries NO answer key — every answer below is worked out and
// verified here. Five figure-based items (32, 33, 38, 40, 43) are rendered as text
// descriptions of the printed diagrams.
5: [
// ---- Mathematics (1-25) ----
{t:"A sentence x + 7 = 5 is", o:["false statement","true statement","not a statement","a statement"], c:2, e:"It contains a free variable, so no truth value can be assigned until x is fixed. Such an open sentence is not a statement."},
{t:"If P and Q are non-empty sets and P ⊂ Q, then", o:["P ⊂ Q′","Q′ ⊂ P′","P ∩ Q = ∅","P ⊃ Q"], c:1, e:"Taking complements reverses inclusion: P ⊂ Q ⟹ Q′ ⊂ P′. (Here ′ denotes complement.)"},
{t:"If |x − 3| = 7 then x =", o:["{10, −4}","[10, −4]","{−8, 4}","(10, −4)"], c:0, e:"x − 3 = 7 gives x = 10; x − 3 = −7 gives x = −4. The solution is the set {10, −4}."},
{t:"√(−1) is", o:["an integer number","a prime number","an irrational number","a complex number"], c:3, e:"√(−1) = i, which is purely imaginary and therefore a complex number (0 + 1i). It is not real, so it cannot be integer, prime or irrational."},
{t:"The range of the function f(x) = √(9 − x²) is", o:["(−3, 3]","[0, 3]","(0, 3)","{0, 2}"], c:1, e:"Domain is [−3, 3]. The square root is non-negative and 9 − x² runs from 0 to 9, so f(x) runs from 0 to 3. Range = [0, 3]."},
{t:"The function f(x) = sin x + x is", o:["even function","period function","odd function","neither even nor odd"], c:2, e:"f(−x) = sin(−x) + (−x) = −sin x − x = −f(x). Sum of two odd functions is odd."},
{t:"If x, y and z are in A.P. then", o:["x + y = z","y + z = 2x","x − z = 2y","x + z = 2y"], c:3, e:"In an A.P. the middle term is the arithmetic mean: y − x = z − y ⟹ 2y = x + z."},
{t:"The determinant of the matrix A = [−3] is", o:["3","not possible","−3","0"], c:2, e:"A is a 1×1 matrix; the determinant of [a] is a itself, so |A| = −3."},
{t:"If x − iy = (5 + 2i)² then (x, y) is", o:["(21, 20)","(21, −20)","(−21, 20)","(−21, −20)"], c:1, e:"(5+2i)² = 25 + 20i + 4i² = 21 + 20i. Comparing x − iy = 21 + 20i gives x = 21 and −y = 20, so y = −20."},
{t:"If in a triangle ABC, the angles are in A.P. then angle B =", o:["30°","45°","120°","60°"], c:3, e:"If A, B, C are in A.P. then 2B = A + C. With A + B + C = 180°, 3B = 180° ⟹ B = 60°."},
{t:"The area of triangle ABC is", o:["2bc sinA","bc sinA","½ bc sinA","½ ac sinA"], c:2, e:"Area = ½ × (product of two sides) × sine of included angle. Sides b and c enclose angle A, so Area = ½ bc sinA."},
{t:"Equation of a line perpendicular to the line 2x + 3y + 5 = 0 is", o:["3x − 2y + 7 = 0","2x − 3y + 7 = 0","−3x − 2y − 7 = 0","−2x − 3y + 7 = 0"], c:0, e:"The given line has slope −2/3, so a perpendicular has slope 3/2. Any line 3x − 2y + k = 0 has slope 3/2. Only option (a) fits; the others are parallel or have the wrong slope."},
{t:"The two lines represented by ax² + 4xy + 2y² = 0 are perpendicular to each other for a =", o:["0","−2","2","1"], c:1, e:"For the pair ax² + 2hxy + by² = 0, the lines are perpendicular when a + b = 0. Here a + 2 = 0 ⟹ a = −2."},
{t:"Equation of tangent at (3, 4) to the circle x² + y² = 25 is", o:["3x − 4y = 25","3x + 4y = −25","4x + 3y = 25","3x + 4y = 25"], c:3, e:"Tangent to x² + y² = a² at (x₁, y₁) is xx₁ + yy₁ = a². Here 3x + 4y = 25."},
{t:"The unit vector along the vector 3i + 4j is", o:["i + j","⅕(3i − 4j)","⅕(3i + 4j)","⅕(i + j)"], c:2, e:"|3i + 4j| = √(9 + 16) = 5, so the unit vector is (3i + 4j)/5."},
{t:"The scalar product of two vectors 3i − 4j + k and 3i + 4j is", o:["6","−7","0","−7i"], c:1, e:"Dot product = (3)(3) + (−4)(4) + (1)(0) = 9 − 16 = −7. A scalar product is a number, not a vector, which rules out −7i."},
{t:"Probability of getting an even number while rolling a die is", o:["0","1/3","1/4","1/2"], c:3, e:"Even outcomes are 2, 4, 6 — that is 3 out of 6 equally likely faces, so P = 3/6 = 1/2."},
{t:"lim(x→3) (x³ − 27)/(x − 3) =", o:["3","9","27","0/0"], c:2, e:"x³ − 27 = (x − 3)(x² + 3x + 9). Cancelling gives x² + 3x + 9 → 9 + 9 + 9 = 27. (Equivalently it is the derivative of x³ at x = 3, i.e. 3·3² = 27.)"},
{t:"The values of x for which dy/dx = 0, for y = x³ − 3x² are", o:["0, 0","0, 2","0, −2","0, 3/2"], c:1, e:"dy/dx = 3x² − 6x = 3x(x − 2) = 0 ⟹ x = 0 or x = 2."},
{t:"If y = e^(log x²) then dy/dx =", o:["2x","yx","2x/y","e^(log x²)"], c:0, e:"e^(log x²) = x², so y = x² and dy/dx = 2x."},
{t:"The point of inflection of y = x³ − x² is", o:["3","0","1/3","1"], c:2, e:"y′ = 3x² − 2x, y″ = 6x − 2. Setting y″ = 0 gives x = 1/3, and y″ changes sign there, so it is a point of inflection."},
{t:"∫₀¹ 3x² e^(x³) dx =", o:["e − 1","e","0","e³"], c:0, e:"Let u = x³, du = 3x² dx. The integral becomes ∫₀¹ eᵘ du = e¹ − e⁰ = e − 1."},
{t:"Area bounded by x-axis, the curve y = x² and the lines x = 0 and x = 4 is", o:["64","16","16/3","64/3"], c:3, e:"Area = ∫₀⁴ x² dx = [x³/3]₀⁴ = 64/3."},
{t:"If f(x) = x² + 5, then the approximate value of f ′(2) with x = 0.1 is", o:["6","4.1","4.2","2"], c:2, e:"f ′(x) = 2x. Advancing the point by δx = 0.1 gives f ′(2.1) = 2(2.1) = 4.2. (Careless reading gives 4 — the increment is the whole point of the question.)"},
{t:"If two forces P and Q, P > Q, are acting at a point of a body, in the same direction, then the resultant force is", o:["P − Q","P + Q","PQ","Q − P"], c:1, e:"Forces in the same direction add directly: R = P + Q. (P − Q is the resultant when they are opposite.)"},
// ---- Physics (26-50) ----
{t:"A quantity x is related by x = (π/3)(a² − b²)h where a, b and h are lengths, then quantity x is", o:["length","velocity","area","volume"], c:3, e:"(a² − b²) has dimension L² and h has L, so x has dimension L³ — a volume. (It is the frustum-type volume formula.)"},
{t:"A vector is multiplied by −2, then", o:["direction reverses and unit changes","direction reverses and magnitude is doubled","direction remains unchanged but unit changes","neither direction reverses nor unit changes but magnitude is doubled"], c:1, e:"The negative sign reverses direction; the factor 2 doubles the magnitude. Multiplying by a pure number never changes the unit."},
{t:"A stone is dropped from a height of 45 m. The distance travelled by it during its last second is", o:["5 m","10 m","25 m","50 m"], c:2, e:"45 = ½gt² with g = 10 gives t = 3 s. Distance in the nth second = ½g(2n − 1) = ½(10)(2·3 − 1) = 25 m."},
{t:"A projectile is broken into two pieces at the maximum height. Then its", o:["momentum increases","momentum decreases","kinetic energy increases","kinetic energy decreases"], c:2, e:"The explosion is driven by internal (chemical) energy, which converts into kinetic energy of the fragments. Momentum is conserved because the explosive forces are internal."},
{t:"Jet plane is based on the conservation of", o:["mass","energy","linear momentum","angular momentum"], c:2, e:"Exhaust gases are thrown backward, so the plane gains forward momentum — conservation of linear momentum (the same principle as a rocket)."},
{t:"Which of the following possesses highest viscosity?", o:["water","blood","glycerine","honey"], c:3, e:"Honey is the most viscous of the four; the usual order is water < blood < glycerine < honey."},
{t:"The graph of kinetic energy (KE) of a body versus velocity (v) is represented as [printed options: (a) a straight line rising from the origin, (b) a curve rising steeply then flattening, (c) a curve that rises slowly and then steepens — concave up, (d) a horizontal straight line]", o:["straight line through the origin","curve rising then flattening (concave down)","curve rising with increasing steepness (concave up, parabolic)","horizontal straight line"], c:2, e:"KE = ½mv², so KE ∝ v². The graph is a parabola through the origin — concave up, getting steeper as v grows. It is NOT a straight line; that trap catches people who think of momentum (p = mv)."},
{t:"A mass m is attached with two identical springs, one on each side fixed to walls, and has frequency f. If one of the springs is removed, the frequency will be", o:["f","2f","f√2","f/√2"], c:3, e:"Two springs on opposite sides act in parallel: k_eff = 2k, so f = (1/2π)√(2k/m). With one spring, f ′ = (1/2π)√(k/m) = f/√2."},
{t:"A metal sheet has a circular hole in it. When it is heated, diameter of the hole", o:["increases","decreases","remains unchanged","first increases and then decreases"], c:0, e:"A hole expands exactly like the material that would fill it. Every linear dimension scales by (1 + αΔT), so the diameter increases."},
{t:"The mean free path of a gas varies with pressure P as", o:["P","P⁻¹","P⁻²","P²"], c:1, e:"λ = kT/(√2 πd²P), so at constant temperature λ ∝ 1/P. Higher pressure packs molecules closer, shortening the free path."},
{t:"A body initially at 100°C cools to 60°C in 5 minutes and to 40°C in 10 minutes. The temperature of the body at the end of 15 minutes will be", o:["35°C","30°C","25°C","20°C"], c:1, e:"By Newton's law of cooling the excess temperatures form a G.P.: (60 − θ₀)² = (100 − θ₀)(40 − θ₀) ⟹ θ₀ = 20°C. Ratio per 5 min = 40/80 = ½. At 15 min excess = 20 × ½ = 10, so temperature = 30°C. ⚠ The printed paper drops the 5-minute temperature; 60°C is reconstructed because it is the only value making the data consistent."},
{t:"Light of wavelength 550 nm falls normally on a slit of width 22 × 10⁻⁷ m. The angular position of the second minima from the central maxima will be", o:["14.5°","42°","30°","62°"], c:2, e:"Single-slit minima: a sinθ = nλ. sinθ = 2(550×10⁻⁹)/(22×10⁻⁷) = 1.1×10⁻⁶/2.2×10⁻⁶ = 0.5 ⟹ θ = 30°."},
{t:"The variation of intensity with wavelength at different temperatures is shown in the figure (three black-body curves; the curve labelled T₁ peaks at the shortest wavelength, T₂ next, T₃ at the longest wavelength). The correct order is", o:["T₁ > T₂ > T₃","T₁ > T₃ > T₂","T₂ > T₃ > T₁","T₃ > T₂ > T₁"], c:0, e:"Wien's displacement law: λ_max T = constant, so the curve peaking at the SHORTEST wavelength is the hottest. Peak order λ₁ < λ₂ < λ₃ gives T₁ > T₂ > T₃."},
{t:"A completely transparent material will be invisible in vacuum when refractive index (μ) is", o:["unity","more than unity","less than unity","infinity"], c:0, e:"Visibility comes from refraction and reflection at the boundary. If μ = 1, matching vacuum, no light bends or reflects at the surface, so the object cannot be seen."},
{t:"For a convex mirror, the variation of u and v is given by [printed options: (a) a curve rising steeply then flattening towards a limit, (b) a straight line through the origin, (c) a falling hyperbola-like curve, (d) a straight line with negative slope]", o:["curve rising and saturating at a limiting value","straight line through the origin","falling hyperbola-like curve","straight line with negative slope"], c:0, e:"1/v + 1/u = 1/f. For a convex mirror the image is always virtual: as u → 0, v → 0, and as u → ∞, v → f. So v grows and saturates at the focal length — a rising curve that flattens."},
{t:"Sweetness of sound depends upon its", o:["wavelength","periodicity","periodicity and regularity","amplitude"], c:2, e:"A sound is pleasant (musical) when the waveform repeats regularly. Pitch depends on frequency and loudness on amplitude, but sweetness needs both periodicity AND regularity of the waveform."},
{t:"A parallel plate capacitor is charged and the charging battery is then disconnected. If the plates of the capacitor are removed further apart by means of insulating handles", o:["The charge on the capacitor increases","The voltage across the plate increases","The capacitance increases","The energy stored decreases"], c:1, e:"With the battery removed, Q is fixed. C = ε₀A/d falls as d increases, so V = Q/C rises and U = Q²/2C also rises (you do work pulling the plates apart)."},
{t:"In the printed network, four 10Ω resistors form the four arms of a bridge between X and Y with a 20Ω resistor as the bridge (galvanometer) arm. The equivalent resistance between the points X and Y is", o:["10 Ω","20 Ω","30 Ω","40 Ω"], c:0, e:"The bridge is balanced (10/10 = 10/10), so no current flows through the 20Ω arm and it can be ignored. Each path is 10 + 10 = 20Ω, and the two 20Ω paths in parallel give 10Ω. ⚠ This item is figure-dependent — check the printed diagram against this reading before trusting the key."},
{t:"A magnetic needle kept in a non-uniform magnetic field. It experiences", o:["torque but not a force","neither a force nor a torque","force and a torque","a force but not a torque"], c:2, e:"In a uniform field the two poles feel equal and opposite forces — torque only. In a NON-uniform field the pole forces differ in magnitude, so there is a net force as well as a torque."},
{t:"A source of 34 V and 50 Hz is connected in series with a coil of 17 mH and a resistor of 10Ω. The potential difference across the coil is", o:["12 V","16 V","28 V","32 V"], c:1, e:"X_L = 2πfL = 2π(50)(0.017) ≈ 5.34Ω. Z = √(10² + 5.34²) ≈ 11.34Ω. I = 34/11.34 ≈ 3.0 A. V_coil = I·X_L ≈ 3.0 × 5.34 ≈ 16 V."},
{t:"A strong argument for particle nature of cathode rays is that they", o:["Produce fluorescence","Travel through vacuum","Get deflected by electric and magnetic fields","Cast shadow"], c:2, e:"Electromagnetic waves are not deflected by electric or magnetic fields; only charged particles are. Fluorescence, travelling through vacuum and casting shadows are all consistent with waves too."},
{t:"When objects placed in a room are exposed to X-rays, they appear", o:["invisible","yellow","blue","red"], c:0, e:"X-rays lie far outside the visible spectrum, so the eye receives nothing from them — the objects remain invisible under X-ray illumination alone."},
{t:"Which series of Hydrogen atom lies in the infrared region?", o:["Lyman","Balmer","Pfund","H-alpha"], c:2, e:"Lyman is ultraviolet, Balmer is visible; Paschen, Brackett and Pfund are all infrared. H-alpha is a single Balmer line (visible red)."},
{t:"When Boron (₅B¹⁰) is bombarded by neutron, alpha particles are emitted. The resulting nucleus has the mass number", o:["11","7","6","15"], c:1, e:"₅B¹⁰ + ₀n¹ → X + ₂He⁴. Mass number: 10 + 1 − 4 = 7 (and atomic number 5 + 0 − 2 = 3, so X is ₃Li⁷)."},
{t:"In P-type semiconductor, the majority and minority charge carriers are respectively", o:["Protons and electrons","Electrons and protons","Electrons and holes","Holes and electrons"], c:3, e:"P-type is doped with trivalent (acceptor) impurity, creating holes as majority carriers; thermally generated electrons are the minority carriers. Protons are never charge carriers in a semiconductor."},
// ---- Chemistry (51-75) ----
{t:"The weight of sodium carbonate required to prepare 100 mL of its decinormal solution is", o:["0.53 g","5.3 g","0.053 g","5.6 g"], c:0, e:"Equivalent weight of Na₂CO₃ = 106/2 = 53. w = N × E × V(L) = 0.1 × 53 × 0.1 = 0.53 g."},
{t:"The concept of pH was introduced by", o:["Arrhenius","Lewis","Bronsted","Sorensen"], c:3, e:"S. P. L. Sorensen introduced the pH scale in 1909. Arrhenius, Bronsted and Lewis gave acid–base theories, not the pH notation."},
{t:"The rate of a chemical reaction increases with", o:["increase in particle size of the reactants","increase in temperature","decrease in temperature","decrease in concentration of reactants"], c:1, e:"Higher temperature means more molecules exceed the activation energy, so the rate rises (roughly doubling per 10°C). Larger particle size REDUCES surface area and slows the rate."},
{t:"A spontaneous change is one in which the system has", o:["an increase in internal energy","lowering of entropy","lowering of free energy","no energy change"], c:2, e:"A process is spontaneous at constant T and P when ΔG < 0, i.e. the free energy decreases. Entropy of the universe increases, not decreases."},
{t:"Which of the following is an example of transition metal?", o:["cobalt","potassium","magnesium","silicon"], c:0, e:"Cobalt (Z = 27) has a partially filled d-subshell — a d-block transition metal. Potassium is s-block, magnesium s-block, silicon p-block."},
{t:"Which of the following compound is called blue vitriol?", o:["Cu₂O","CuSO₄·5H₂O","CuCl₂","Cu₂Cl₂"], c:1, e:"Blue vitriol is hydrated copper(II) sulphate, CuSO₄·5H₂O. (Green vitriol = FeSO₄·7H₂O, white vitriol = ZnSO₄·7H₂O.)"},
{t:"Silver is extracted from its sulphide ore by", o:["Contact process","Down's process","Cyanide process","Ostwald's process"], c:2, e:"The MacArthur–Forrest cyanide process leaches Ag₂S with dilute NaCN and displaces silver with zinc. Contact = H₂SO₄, Down's = Na metal, Ostwald's = HNO₃."},
{t:"2,4-Dichlorophenoxyacetic acid (2,4-D) is generally used as", o:["a herbicide","an insecticide","a fungicide","none of the above"], c:0, e:"2,4-D is a selective synthetic auxin herbicide used to kill broad-leaved weeds."},
{t:"A class of organometallic compounds of magnesium with the general formula RMgX (where R is an organic group and X is a halogen atom) is known as", o:["Tollen's reagent","Nessler's reagent","Schiff's reagent","Grignard reagent"], c:3, e:"RMgX is the Grignard reagent. Tollen's = ammoniacal AgNO₃, Nessler's = K₂HgI₄, Schiff's = fuchsin/SO₂."},
{t:"Aldehydes can be distinguished from ketones by", o:["Fehling's solution","conc. H₂SO₄","Grignard's reagent","pyragallol"], c:0, e:"Aldehydes reduce Fehling's solution to a red Cu₂O precipitate; ketones do not. (Tollen's reagent works the same way.)"},
{t:"Picric acid is obtained by the nitration of", o:["aniline","phenol","benzene","benzoic acid"], c:1, e:"Picric acid is 2,4,6-trinitrophenol, made by nitrating phenol (usually via phenol-2,4-disulphonic acid). Nitrating benzene gives nitrobenzene/TNB, not picric acid."},
{t:"Which of the following compound is used as an anaesthetic?", o:["ethylene","ethyl alcohol","chloroform","acetylene"], c:2, e:"Chloroform (CHCl₃) was the classical general anaesthetic. Ethyl alcohol is an antiseptic/solvent, and ethylene/acetylene are not used this way."},
{t:"Aromatic carboxylic acid is", o:["formic acid","acetic acid","stearic acid","cinnamic acid"], c:3, e:"Cinnamic acid (C₆H₅CH=CH−COOH) is the only one containing a benzene ring. Formic, acetic and stearic acids are all aliphatic."},
{t:"Which of the following compound is called urea?", o:["NH₂CONH₂","NH₂COONH₄","H₂NNHCONH₂","H₂NCONHC₂H₅"], c:0, e:"Urea is carbamide, NH₂CONH₂. NH₂COONH₄ is ammonium carbamate; H₂NNHCONH₂ is semicarbazide."},
{t:"Ethyne reacts with alkaline KMnO₄ solution to give", o:["glyoxal","oxalic acid","ethanoic acid","acetic acid"], c:1, e:"Alkaline KMnO₄ (Baeyer's reagent) oxidises the triple bond right through to oxalic acid, HOOC−COOH. The pink colour discharging is the classic unsaturation test."},
{t:"IUPAC name of acetaldehyde is", o:["methanal","propanal","ethanal","butanal"], c:2, e:"Acetaldehyde is CH₃CHO — two carbons with a −CHO group, so ethanal. Methanal is HCHO (formaldehyde)."},
{t:"Which is the most toxic chemical form of mercury?", o:["Hg","Hg₂²⁺","Hg²⁺","CH₃Hg⁺"], c:3, e:"Methylmercury (CH₃Hg⁺) is lipid-soluble, bioaccumulates up the food chain and crosses the blood–brain barrier — the agent of Minamata disease."},
{t:"The number of molecules in 32 g of oxygen is", o:["6.02 × 10²³","6.02 × 10⁹","3.2 × 10²³","3.2 × 10¹⁶"], c:0, e:"Molar mass of O₂ is 32 g/mol, so 32 g is exactly 1 mole = 6.02 × 10²³ molecules."},
{t:"The outermost electronic configuration of chromium is", o:["3d⁴4s²","3d⁵4s¹","3d⁵4s²","3d⁶4s²"], c:1, e:"Chromium (Z = 24) promotes one 4s electron to give the extra-stable half-filled d-subshell: [Ar]3d⁵4s¹. (Copper does the same to reach 3d¹⁰4s¹.)"},
{t:"Which of the following has the lowest ionic radius?", o:["O²⁻","F⁻","Al³⁺","Na⁺"], c:2, e:"All four are isoelectronic (10 electrons). The one with the highest nuclear charge pulls hardest, so radius falls as Z rises: O²⁻ > F⁻ > Na⁺ > Al³⁺ (Z = 13)."},
{t:"Which of the following hydrogen halides has the lowest dipole moment?", o:["HF","HCl","HBr","HI"], c:3, e:"Electronegativity difference falls down the group, so polarity falls: HF > HCl > HBr > HI. HI is the least polar."},
{t:"The value of universal gas constant (R) in SI unit is", o:["8.314 joule k⁻¹ mol⁻¹","5.314 joule k⁻¹ mol⁻¹","3.501 joule k⁻¹ mol⁻¹","8.314 × 10⁷ ergs k⁻¹ mol⁻¹"], c:0, e:"R = 8.314 J K⁻¹ mol⁻¹. The erg value (8.314 × 10⁷) is numerically right but erg is CGS, not SI."},
{t:"An example of acidic oxide is", o:["NO","N₂O₅","N₂O","Al₂O₃"], c:1, e:"N₂O₅ dissolves in water to give HNO₃, so it is acidic. NO and N₂O are neutral oxides; Al₂O₃ is amphoteric."},
{t:"The ionic character in H−X bond is highest in", o:["HCl","HBr","HF","HI"], c:2, e:"Ionic character follows electronegativity difference, which is largest for H−F. HF is about 43% ionic, the highest of the hydrogen halides."},
{t:"Which of the following compounds is called magnesia?", o:["MgSO₄·7H₂O","MgCl₂·6H₂O","MgCl₂","Mg(OH)₂"], c:3, e:"Of the four, only Mg(OH)₂ carries the name magnesia (milk of magnesia). MgSO₄·7H₂O is Epsom salt. ⚠ Strictly, 'magnesia' alone means MgO, which is not offered here."},
// ---- English (76-90) ----
{t:"The word “headhunter” gets its prime stress on:", o:["1st syllable","2nd syllable","3rd syllable","none"], c:0, e:"Compound nouns in English take primary stress on the first element: HEAD-hunter, like BLACKboard and GREENhouse."},
{t:"Pick out the word or group of words which has nearly the same meaning as the word “headland”:", o:["highland","flat land","promontory","marshy land"], c:2, e:"A headland is a point of land jutting out into the sea — a promontory. Highland is merely elevated ground, with no sense of projecting into water."},
{t:"Pick out the word or group of words which has nearly the same meaning as the word “remarkable”:", o:["good","astonishing","commendable","notable"], c:3, e:"Remarkable = worth remarking on, i.e. notable. Astonishing is far stronger, and commendable means praiseworthy, which is a different idea."},
{t:"Pick out the word or group of words which has nearly the opposite meaning as the word “pompous”:", o:["showy","wealthy","convincing","humble"], c:3, e:"Pompous means self-important and puffed up; its opposite is humble. Showy is a near-synonym, not an antonym."},
{t:"Pick out the word or group of words which has nearly the opposite meaning as the word “reciprocal”:", o:["obstinate","unilateral","mutual","imaginary"], c:1, e:"Reciprocal means given and received on both sides; unilateral means one-sided. Mutual is a synonym — the classic trap in this item."},
{t:"Writing with correct spelling is:", o:["orthography","homograph","telegraphy","lithography"], c:0, e:"Orthography is the study or practice of correct spelling. A homograph is a same-spelling word; lithography is a printing process."},
{t:"Choose the correct word order in the expression “We ... cruelty, ... tyranny and ... a flatterer.”", o:["hate, abhor, loathe","abhor, hate, loathe","loathe, hate, abhor","abhor, loathe, hate"], c:0, e:"The established collocations are: hate cruelty, abhor tyranny, loathe a flatterer — rising in intensity and matching the usual objects of each verb."},
{t:"Belief that God is nature:", o:["Henotheism","Polytheism","Pantheism","Deism"], c:2, e:"Pantheism identifies God with nature/the universe. Henotheism = one god among many; polytheism = many gods; deism = a creator who does not intervene."},
{t:"Choose correct prepositions for the given expression “For a week she lived ... banana and milk as she believed .... the prescription of her doctor.”", o:["at, on","on, in","in, on","on, on"], c:1, e:"You live ON a diet of something, and you believe IN a person or prescription (trusting it). Hence: on, in."},
{t:"Choose correct prepositions for the given expression “I am scared.... loss ...my business but keen ...gambling.”", o:["in, of, on","on, in, of","in, on, of","of, in, on"], c:3, e:"Scared OF something, loss IN business, keen ON an activity. Hence: of, in, on."},
{t:"Pick up the correct phrasal verb for the expression: “I was the son of sailors and ....stories of the sea.”", o:["reared on","reared off","brought on","put on"], c:0, e:"To be reared ON something means to be brought up nourished by it — used figuratively here for the stories he grew up with."},
{t:"Pick up the correct phrasal verb for the expression: “when does school...for the summer vacation?”", o:["break out","break up","break off","break in"], c:1, e:"School breaks up = term ends for the holidays. Break out = start suddenly (war, fire); break off = stop abruptly; break in = enter forcibly."},
{t:"Give the exact meaning of the idiomatic expression “Bright and breezy”", o:["in very sad mood","in very active mood","in a cheerful mood to do things quickly","in decisive mood"], c:2, e:"Bright and breezy describes someone lively and cheerful, getting on with things briskly — it carries both the cheer and the speed."},
{t:"Give the exact meaning of the idiomatic expression: “Go by the board”", o:["plans discontinued and abandoned","plans in action","with a new plane","no plan for sometime"], c:0, e:"From the sailing term for something falling overboard past the ship's side: to go by the board is to be abandoned or come to nothing."},
{t:"Use correct conditional expression in the expression : “You must go tomorrow ...you are ready or not.”", o:["if","even if","unless","whether"], c:3, e:"The “... or not” construction requires whether: whether you are ready or not. If cannot take “or not” in this position."},
// ---- Computer Related GK (91-100) ----
{t:"MS-Word is an example of", o:["An operating system","A processing device","Application software","An input device"], c:2, e:"MS-Word is a program written to do a user task, so it is application software. System software (like Windows) runs the machine itself."},
{t:"A computer cannot “boot” if it does not have the", o:["Compiler","Loader","Operating system","Assembler"], c:2, e:"Booting means loading the operating system into RAM. Without an OS there is nothing to load, so the machine cannot boot."},
{t:"By default, your documents print in ................ mode.", o:["Landscape","Portrait","Page Setup","Print View"], c:1, e:"Portrait (taller than wide) is the default page orientation. Page Setup and Print View are dialogs, not modes of printing."},
{t:"Ctrl, Shift and Alt are called .................. keys.", o:["modifier","function","alphanumeric","adjustment"], c:0, e:"They modify the meaning of another key pressed with them, hence modifier keys. Function keys are F1–F12."},
{t:"Storage which stores or retains data after power off is called", o:["Volatile storage","Non-volatile storage","Sequential storage","Direct storage"], c:1, e:"Non-volatile storage (hard disk, SSD, ROM) keeps its contents without power. RAM is volatile. Sequential/direct describe access method, not persistence."},
{t:"What are the four things needed to connect to the internet?", o:["telephone line, modem, computer, and an ISP","modem, computer, PDA, and ISP","telephone line, modem, computer, and PDA","computer, ISP, modem, and communication software"], c:0, e:"You need the physical line, a modem to put data on it, a computer, and an ISP to route you onto the internet. A PDA is not required."},
{t:"Which process refers to the starting up of a computer and the loading of the required parts of the operating system into the RAM?", o:["Booting","Tagging","Swipping","Mapping"], c:0, e:"Booting (from “pulling itself up by its bootstraps”) is the startup sequence that loads the OS kernel into RAM."},
{t:"In the context of a word document, the term gutter stands for", o:["the blank page inserted in between two filled pages","the space left on the left side for rough work","the space between two paragraphs","the space left on one side for stitching and binding"], c:3, e:"The gutter is extra margin added on the binding side so text is not swallowed when the document is stitched or bound."},
{t:"Programs stored in ROM are called as", o:["Fireware","Formware","Farmware","Firmware"], c:3, e:"Firmware is software written permanently into ROM (e.g. BIOS). The other three spellings are not words — this item is purely a spelling trap."},
{t:"Select the correct statement from the following statements: A. MS-Excel creates workbooks, and each workbook may contain more work sheets. B. A worksheet in MS-Excel 2000 package has a maximum of 256 columns and 65536 rows. C. Columns are identified by a number and rows are identified by a letter. D. Cells are identified by the column letter and the row number.", o:["A, B, C","B, C, D","C, D, A","A, B, D"], c:3, e:"A, B and D are correct. C is reversed — columns carry LETTERS (A, B, C…) and rows carry NUMBERS (1, 2, 3…), which is exactly what D states. Any option containing C must be wrong."},
],
};
